/* REWORDS ADMIN — rewritten from scratch against admin.html/style.css. */
{firebase}
const db=firebase.firestore(), auth=firebase.auth();
const ts=()=>firebase.firestore.FieldValue.serverTimestamp(); const inc=n=>firebase.firestore.FieldValue.increment(Number(n)||0);
const el=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>(['&','<','>','\"'].includes(c)?{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]:c));
const fmt=n=>Number(n||0).toLocaleString('en-US'); const now=()=>Date.now();
const ADMIN={user:null,doc:null,role:null,permissions:new Set(),page:'dashboard',orderFilter:'all',ledgerFilter:'all',data:{}};
const DEFAULT={coinRate:10000,signupBonus:100,minWithdraw:10000,withdrawalFeePct:1,referralPercent:10,maintenance:false,allowSignups:true,adReward:120,adDailyCap:15,supportEmail:'support@rewords.com',siteUrl:location.origin,announcement:''};
function toast(t,m,type='info'){const w=el('adminToastWrap');if(!w)return;const n=document.createElement('div');n.className='toast '+type;n.innerHTML=`<div class="toast-title">${esc(t)}</div><div class="toast-msg">${esc(m)}</div>`;w.appendChild(n);setTimeout(()=>n.remove(),4500);}
function handleErr(e,msg='Operation failed'){console.error(e);toast('Error',e?.message||msg,'error');}
function closeAdminModal(id){el(id)?.classList.remove('open');}
function openAdminModal(title,html){setText('adminGenericModalTitle',title);el('adminGenericModalBody').innerHTML=html;el('adminGenericModal').classList.add('open');}
function setText(id,v){const n=el(id);if(n)n.textContent=v??'';}
function can(p){return ADMIN.permissions.has('*')||ADMIN.permissions.has(p);}
function requirePerm(p){if(!can(p)){toast('Permission denied','You do not have '+p,'warning');return false}return true;}
function modalConfirm(title,body,ok='Confirm'){return new Promise(resolve=>{openAdminModal(title,`<p>${esc(body)}</p><div class="flex gap-2 mt-3"><button class="btn btn-ghost" data-confirm="no">Cancel</button><button class="btn btn-danger" data-confirm="yes">${esc(ok)}</button></div>`);const wrap=el('adminGenericModalBody');wrap.onclick=e=>{const b=e.target.closest('[data-confirm]');if(!b)return;closeAdminModal('adminGenericModal');resolve(b.dataset.confirm==='yes');};})}
function csv(name,rows){const s=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+s],{type:'text/csv'}));a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function downloadJSON(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name+'.json';a.click();}
async function col(name,limit=500){const s=await db.collection(name).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
async function get(name,id){const d=await db.collection(name).doc(id).get();return d.exists?{id:d.id,...d.data()}:null;}
async function audit(action,details=''){if(!can('logs.write'))return;await db.collection('admin_logs').add({action,details,adminId:ADMIN.user.uid,adminEmail:ADMIN.user.email,ts:now(),createdAt:ts()}).catch(()=>{});}

async function verifyAdmin(user){const d=await get('admin_users',user.uid);if(!d||d.active===false)return null;return d;}
async function login(e){e.preventDefault();const b=el('adminLoginBtn');b.disabled=true;try{const email=el('adminEmail').value.trim(),pw=el('adminPassword').value;if(!email||!pw)throw new Error('Email and password are required.');await auth.signInWithEmailAndPassword(email,pw);}catch(e){handleErr(e,'Admin login failed');}finally{b.disabled=false;}}
async function logout(){await auth.signOut().catch(()=>{});}
async function initAuth(){auth.onAuthStateChanged(async user=>{if(!user){showLogin(false);return;}const doc=await verifyAdmin(user);if(!doc){showLogin(true);await auth.signOut();return;}ADMIN.user=user;ADMIN.doc=doc;ADMIN.role=doc.role||'staff';ADMIN.permissions=new Set(Array.isArray(doc.permissions)?doc.permissions:[]);showShell();await refreshAll();});}
function showLogin(denied){el('adminAuth').style.display='grid';el('adminShell').style.display='none';el('adminAccessDenied')?.classList.toggle('hidden',!denied);}
function showShell(){el('adminAuth').style.display='none';el('adminShell').style.display='flex';}

const COLLECTIONS=['users','offers','providers','games','surveys','rewards','orders','withdrawals','tickets','promos','events','posts','faqs','ledger','admin_logs','fraud_events','referrals'];
async function refreshAll(){const results=await Promise.all(COLLECTIONS.map(n=>col(n).catch(()=>[])));COLLECTIONS.forEach((n,i)=>ADMIN.data[n]=results[i]);ADMIN.data.settings=await get('settings','global')||{...DEFAULT};renderPage(ADMIN.page);updateBadges();}
function updateBadges(){setText('sideBadgeUsers',ADMIN.data.users?.filter(x=>x.status==='active').length||0);setText('sideBadgeFraud',ADMIN.data.fraud_events?.length||0);setText('sideBadgeOrders',ADMIN.data.orders?.filter(x=>x.status==='pending').length||0);setText('sideBadgeWithdrawals',ADMIN.data.withdrawals?.filter(x=>x.status==='pending').length||0);setText('sideBadgeTickets',ADMIN.data.tickets?.filter(x=>['open','pending'].includes(x.status)).length||0);}
function nav(page){ADMIN.page=page;$$('[data-admin-nav]').forEach(x=>x.classList.toggle('active',x.dataset.adminNav===page));$$('.admin-page').forEach(x=>x.classList.toggle('active',x.id==='admin-'+page));renderPage(page);}
function table(rows,headers,keys,actions=''){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'—')}</td>`).join('')}${actions?`<td>${actions.replaceAll('{id}',r.id)}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function setGrid(id,html){const n=el(id);if(n)n.innerHTML=html||'<div class="empty-state"><div class="es-title">No data</div></div>';}
function renderDashboard(){const u=ADMIN.data.users||[],o=ADMIN.data.offers||[],w=ADMIN.data.withdrawals||[],ord=ADMIN.data.orders||[],t=ADMIN.data.tickets||[],led=ADMIN.data.ledger||[];setText('kpiTotalUsers',u.length);setText('kpiCoins',fmt(u.reduce((s,x)=>s+Number(x.balance||0),0)));setText('kpiWithdrawn',fmt(u.reduce((s,x)=>s+Number(x.totalWithdrawn||0),0)));setText('kpiGrowth',u.filter(x=>x.createdAt).length);setText('qsUsers',u.length);setText('qsOffers',o.length);setText('qsWithdrawals',w.filter(x=>x.status==='pending').length);setText('qsOrders',ord.filter(x=>x.status==='pending').length);setText('qsTickets',t.filter(x=>x.status==='open').length);setText('qsFlagged',(ADMIN.data.fraud_events||[]).length);setText('qsRevenue',fmt(led.filter(x=>Number(x.coins)<0).reduce((s,x)=>s+Math.abs(Number(x.coins||0)),0)));setText('qsProfit','—');setGrid('dashTopOffers',o.slice(0,5).map(x=>`<div class="card"><b>${esc(x.title)}</b><span>+${fmt(x.payout||0)}</span></div>`).join(''));setGrid('dashRecentActivity',led.slice(0,10).map(x=>`<div class="card"><b>${esc(x.description||x.type)}</b><span>${fmt(x.coins)}</span></div>`).join(''));setGrid('dashRewardsSold',(ADMIN.data.rewards||[]).slice(0,5).map(x=>`<div class="card"><b>${esc(x.title)}</b><span>${fmt((x.initialStock||x.stock||0)-(x.stock||0))} sold</span></div>`).join(''));}
function renderAnalytics(){setText('anVisits','—');setText('anSignups',(ADMIN.data.users||[]).length);setText('anConversion','—');setText('anSession','—');setText('funnelVisitors','—');setText('funnelSignups',(ADMIN.data.users||[]).length);setText('funnelEarners',(ADMIN.data.users||[]).filter(x=>Number(x.lifetimeEarned)>0).length);setText('funnelDepositors',(ADMIN.data.users||[]).filter(x=>Number(x.lifetimeSpent)>0).length);setText('funnelWithdrawers',(ADMIN.data.users||[]).filter(x=>Number(x.totalWithdrawn)>0).length);}
function renderFinance(){const f=ADMIN.ledgerFilter||'all';const led=(ADMIN.data.ledger||[]).filter(x=>f==='all'||x.type===f);setText('finRevenue',fmt(led.filter(x=>Number(x.coins)<0).reduce((s,x)=>s+Math.abs(Number(x.coins||0)),0)));setText('finRewards',fmt(led.filter(x=>x.type==='reward').reduce((s,x)=>s+Math.abs(Number(x.coins||0)),0)));setText('finPayments',fmt((ADMIN.data.withdrawals||[]).filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.receive||x.amount||0),0)));setText('finReserve',fmt((ADMIN.data.users||[]).reduce((s,x)=>s+Number(x.balance||0),0)));setText('finProfit','—');setText('finMargin','—');setGrid('financeLedgerList',table(led.slice(0,100),['Type','UID','Coins','Status'],['type','uid','coins','status']));}
function renderUsers(){const q=(el('usersSearch')?.value||'').toLowerCase();const rows=(ADMIN.data.users||[]).filter(u=>JSON.stringify(u).toLowerCase().includes(q));setText('usActive',rows.filter(u=>u.status==='active').length);setText('usPending',rows.filter(u=>u.status==='pending').length);setText('usBanned',rows.filter(u=>u.status==='banned').length);setText('usFlagged',rows.filter(u=>u.fraudFlag).length);setGrid('usersTable',table(rows,['Username','Email','Balance','Status'],['username','email','balance','status'],`<button class="btn btn-sm btn-ghost" data-admin-action="viewUser" data-id="{id}">View</button>`));}
function renderOffers(){const q=(el('offersSearch')?.value||'').toLowerCase();const rows=(ADMIN.data.offers||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(q));setGrid('offersTable',table(rows,['Title','Provider','Payout','Active'],['title','provider','payout','active'],`<button class="btn btn-sm btn-ghost" data-admin-action="editOffer" data-id="{id}">Edit</button> <button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="offers" data-id="{id}">Delete</button>`));}
function renderProviders(){setGrid('providersGrid',(ADMIN.data.providers||[]).map(p=>`<div class="card"><b>${esc(p.name)}</b><div>${esc(p.type||'')}</div><div>Status: ${p.active===false?'disabled':'enabled'}</div><div class="flex gap-2 mt-2"><button class="btn btn-sm btn-ghost" data-admin-action="editProvider" data-id="${p.id}">Edit</button><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="providers" data-id="${p.id}">Delete</button></div></div>`).join(''));}
function renderGames(){setGrid('gamesGrid',(ADMIN.data.games||[]).map(g=>`<div class="card"><b>${esc(g.title)}</b><div>${esc(g.platform||'')}</div><button class="btn btn-sm btn-ghost mt-2" data-admin-action="editGame" data-id="${g.id}">Edit</button></div>`).join(''));}
function renderSurveys(){setGrid('surveysGrid',(ADMIN.data.surveys||[]).map(s=>`<div class="card"><b>${esc(s.title)}</b><div>+${fmt(s.payout||0)}</div><button class="btn btn-sm btn-ghost mt-2" data-admin-action="editSurvey" data-id="${s.id}">Edit</button></div>`).join(''));}
function renderAds(){const s=ADMIN.data.settings||DEFAULT;const ads=s.ads||DEFAULT.ads;['adsterra','monetag','hilltop','popads'].forEach(k=>{const n=el('adNetwork'+k.charAt(0).toUpperCase()+k.slice(1));if(n)n.checked=!!ads[k]?.enabled;});const p=ads.placements||{};[['Banner','banner'],['Native','native'],['Popunder','popunder'],['Socialbar','socialbar'],['Smartlink','smartlink'],['MonetagDirect','monetagDirect']].forEach(([id,key])=>{const n=el('adPlacement'+id);if(n)n.checked=p[key]!==false;});setValue('adsCoinsPerAd',s.adReward||120);setValue('adsDailyCap',s.adDailyCap||15);setValue('adsECPM',s.adECPM||0);}
function renderCampaigns(){setGrid('promosGrid',(ADMIN.data.promos||[]).map(p=>`<div class="card"><b>${esc(p.code)}</b><div>+${fmt(p.reward||0)}</div><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="promos" data-id="${p.id}">Delete</button></div>`).join(''));setGrid('eventsGrid',(ADMIN.data.events||[]).map(p=>`<div class="card"><b>${esc(p.title)}</b><div>${esc(p.status||'active')}</div><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="events" data-id="${p.id}">Delete</button></div>`).join(''));setGrid('postsGrid',(ADMIN.data.posts||[]).map(p=>`<div class="card"><b>${esc(p.title)}</b><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="posts" data-id="${p.id}">Delete</button></div>`).join(''));}
function renderRewards(){const q=(el('rewardsSearch')?.value||'').toLowerCase();setGrid('rewardsGridAdmin',(ADMIN.data.rewards||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(q)).map(r=>`<div class="card"><b>${esc(r.title)}</b><div>Price: ${fmt((r.price??r.cost??0))} · Stock: ${r.stock==null?'∞':fmt(r.stock)}</div><div class="flex gap-2 mt-2"><button class="btn btn-sm btn-ghost" data-admin-action="editReward" data-id="${r.id}">Edit</button><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="rewards" data-id="${r.id}">Delete</button></div></div>`).join(''));}
function renderOrders(){const f=ADMIN.orderFilter||'all';const rows=(ADMIN.data.orders||[]).filter(x=>f==='all'||x.type===f);setText('ordPending',rows.filter(x=>x.status==='pending').length);setText('ordCompleted',rows.filter(x=>x.status==='completed').length);setText('ordRefunded',rows.filter(x=>x.status==='refunded').length);setText('ordValue',fmt(rows.reduce((s,x)=>s+Number(x.cost||0),0)));setGrid('ordersTableBody',table(rows,['UID','Type','Cost','Status'],['uid','type','cost','status'],`<button class="btn btn-sm btn-ghost" data-admin-action="completeOrder" data-id="{id}">Complete</button> <button class="btn btn-sm btn-danger" data-admin-action="refundOrder" data-id="{id}">Refund</button>`));}
function renderWithdrawals(){const rows=ADMIN.data.withdrawals||[];setText('wdPending',rows.filter(x=>x.status==='pending').length);setText('wdApproved',rows.filter(x=>x.status==='approved').length);setText('wdPaid',rows.filter(x=>x.status==='paid').length);setText('wdChargebacks',rows.filter(x=>x.status==='refunded'||x.status==='chargeback').length);setGrid('withdrawalsTableBody',table(rows,['UID','Amount','Method','Status'],['uid','amount','method','status'],`<button class="btn btn-sm btn-ghost" data-admin-action="approveWd" data-id="{id}">Approve</button> <button class="btn btn-sm btn-accent" data-admin-action="payWd" data-id="{id}">Paid</button> <button class="btn btn-sm btn-danger" data-admin-action="rejectWd" data-id="{id}">Reject</button>`));}
function renderFraud(){const rows=ADMIN.data.fraud_events||[];setText('fraudHigh',rows.filter(x=>x.level==='high').length);setText('fraudMed',rows.filter(x=>x.level==='medium').length);setText('fraudVpn',rows.filter(x=>x.type==='vpn').length);setText('fraudEmulator',rows.filter(x=>x.type==='emulator').length);setGrid('fraudEventsBody',table(rows,['UID','Type','Level','Score'],['uid','type','level','score']));}
function renderReferral(){const rows=ADMIN.data.referrals||[];setText('refTotal',rows.length);setText('refActiveReferrers',new Set(rows.map(x=>x.referrerId)).size);setText('refCoinsPaid',fmt((rows||[]).reduce((s,x)=>s+Number(x.commission||0),0)));setText('refFraudBlocked',rows.filter(x=>x.status==='blocked').length);setGrid('referralRecordsBody',table(rows,['Referrer','Referred','Status','Commission'],['referrerId','referredId','status','commission']));}
function renderContent(){setHtml('termsEditor',(ADMIN.data.settings||{}).terms||'');setHtml('privacyEditor',(ADMIN.data.settings||{}).privacy||'');setGrid('faqsList',(ADMIN.data.faqs||[]).map(f=>`<div class="card"><b>${esc(f.q||f.question)}</b><p>${esc(f.a||f.answer)}</p><button class="btn btn-sm btn-danger" data-admin-action="delete" data-col="faqs" data-id="${f.id}">Delete</button></div>`).join(''));const s=ADMIN.data.settings||{};setValue('termsEditor',s.terms||'');setValue('privacyEditor',s.privacy||'');setValue('contentHeroTitle',s.heroTitle||'');setValue('contentHeroSub',s.heroSub||'');setValue('contentBanner',s.banner||'');setGrid('blogPostsGrid',(ADMIN.data.posts||[]).map(p=>`<div class="card"><b>${esc(p.title)}</b><p>${esc(p.content||'')}</p></div>`).join(''));}
function renderSupport(){const t=ADMIN.data.tickets||[];setText('supOpen',t.filter(x=>['open','pending'].includes(x.status)).length);setText('supProgress',t.filter(x=>x.status==='in_progress').length);setText('supResolved',t.filter(x=>x.status==='resolved').length);setGrid('ticketsTableBody',table(t,['UID','Subject','Status','Priority'],['uid','subject','status','priority'],`<button class="btn btn-sm btn-ghost" data-admin-action="viewTicket" data-id="{id}">View</button> <button class="btn btn-sm btn-accent" data-admin-action="resolveTicket" data-id="{id}">Resolve</button>`));}
function renderSettings(){const s={...DEFAULT,...(ADMIN.data.settings||{})};[['setCoinRate',s.coinRate],['setSignupBonus',s.signupBonus],['setMinWithdraw',s.minWithdraw],['setWithdrawFee',s.withdrawalFeePct],['setSiteUrl',s.siteUrl],['setSupportEmail',s.supportEmail],['setAnnouncement',s.announcement]].forEach(([id,v])=>setValue(id,v));const c=el('setSiteUrl');if(c)c.value=s.siteUrl||location.origin;}
function renderSecurity(){const s=ADMIN.data.settings||{};[['setPwMin',8],['setWdDay',s.wdDayCap||0],['setWdWeek',s.wdWeekCap||0],['setTopupDay',s.topupDayCap||0],['setWdMax',s.maxWithdraw||0],['setLoginAttempts',5],['setVpnPenalty',s.vpnPenalty||0],['setEmuPenalty',s.emuPenalty||0],['setDupPenalty',s.dupPenalty||0],['setFlagThreshold',s.flagThreshold||50],['setRestrictThreshold',s.restrictThreshold||75],['setBanThreshold',s.banThreshold||90]].forEach(([id,v])=>setValue(id,v));setGrid('securityEventsList',table((ADMIN.data.fraud_events||[]).slice(0,50),['UID','Type','Level','Score'],['uid','type','level','score']));}
async function renderRoles(){const rows=await col('admin_users',100);setGrid('adminsListBody',table(rows,['Email','Role','Active','Permissions'],['email','role','active','permissions'],`<button class="btn btn-sm btn-danger" data-admin-action="revokeAdmin" data-id="{id}">Revoke</button>`));}
function renderLogs(){setGrid('auditLogsList',table((ADMIN.data.admin_logs||[]).slice(0,200),['Action','Admin','Details'],['action','adminEmail','details']));}
const RENDER={dashboard:renderDashboard,analytics:renderAnalytics,finance:renderFinance,users:renderUsers,offers:renderOffers,providers:renderProviders,games:renderGames,surveys:renderSurveys,ads:renderAds,campaigns:renderCampaigns,rewards:renderRewards,orders:renderOrders,withdrawals:renderWithdrawals,fraud:renderFraud,referral:renderReferral,content:renderContent,support:renderSupport,settings:renderSettings,security:renderSecurity,roles:renderRoles,logs:renderLogs};
function renderPage(p){if(RENDER[p])Promise.resolve(RENDER[p]()).catch(e=>handleErr(e));}
function setValue(id,v){const n=el(id);if(n)n.value=v??'';}

function openOfferEditor(id){if(!requirePerm('offers.write'))return;const o=ADMIN.data.offers?.find(x=>x.id===id)||{};setValue('offerEditId',id||'');setValue('offerEditTitle',o.title||'');setValue('offerEditProvider',o.provider||'');setValue('offerEditCategory',o.category||'');setValue('offerEditDifficulty',o.difficulty||'');setValue('offerEditPayout',o.payout||0);setValue('offerEditMinutes',o.minutes||5);setValue('offerEditIcon',o.icon||'🎯');setValue('offerEditLink',o.link||'');setValue('offerEditDesc',o.description||'');if(el('offerEditActive'))el('offerEditActive').checked=o.active!==false;el('offerEditorModal').classList.add('open');}
function openRewardEditor(id){if(!requirePerm('rewards.write'))return;const r=ADMIN.data.rewards?.find(x=>x.id===id)||{};setValue('rewardEditId',id||'');setValue('rewardEditTitle',r.title||'');setValue('rewardEditCategory',r.category||'');setValue('rewardEditIcon',r.icon||'🎁');setValue('rewardEditPrice',r.price??r.cost??0);setValue('rewardEditStock',r.stock??0);setValue('rewardEditType',r.type||'reward');if(el('rewardEditActive'))el('rewardEditActive').checked=r.active!==false;el('rewardEditorModal').classList.add('open');}
function genericEditor(type,id){const existing=ADMIN.data[type+'s']?.find(x=>x.id===id)||{};const labels={games:['title','platform','link','description','icon'],surveys:['title','payout','minutes','link','description','icon'],providers:['name','type','active','identifier','status']}[type]||['title','description'];openAdminModal((id?'Edit ':'Create ')+type,`<div class="grid grid-2 gap-2">${labels.map(k=>`<label class="field"><span>${esc(k)}</span><input id="gen_${k}" value="${esc(existing[k]??'')}"></label>`).join('')}</div><button class="btn btn-accent mt-3" data-generic-save="${type}" data-id="${id||''}">Save</button>`);}
async function saveGeneric(type,id){if(!requirePerm(type+'s.write'))return;const fields={games:['title','platform','link','description','icon'],surveys:['title','payout','minutes','link','description','icon'],providers:['name','type','active','identifier','status']}[type]||['title','description'];const data={};fields.forEach(k=>data[k]=el('gen_'+k)?.value||'');if(type==='games'||type==='surveys')data.active=true;if(type==='providers')data.active=data.active!=='false';try{const ref=id?db.collection(type+'s').doc(id):db.collection(type+'s').doc();if(id)await ref.update({...data,updatedAt:ts()});else await ref.set({...data,createdAt:ts(),ts:now()});closeAdminModal('adminGenericModal');await refreshAll();await audit(type+'_save',id||ref.id);toast('Saved',type+' saved.','success');}catch(e){handleErr(e)}}

async function saveOffer(e){e.preventDefault();if(!requirePerm('offers.write'))return;const id=el('offerEditId').value||null;const data={title:el('offerEditTitle').value.trim(),provider:el('offerEditProvider').value.trim(),category:el('offerEditCategory').value.trim(),difficulty:el('offerEditDifficulty').value.trim(),payout:Number(el('offerEditPayout').value||0),minutes:Number(el('offerEditMinutes').value||0),icon:el('offerEditIcon').value.trim(),link:el('offerEditLink').value.trim(),description:el('offerEditDesc').value.trim(),active:el('offerEditActive').checked,updatedAt:ts()};try{if(id)await db.collection('offers').doc(id).update(data);else{data.createdAt=ts();data.ts=now();await db.collection('offers').add(data)}closeAdminModal('offerEditorModal');await audit(id?'offer_update':'offer_create',data.title);await refreshAll();toast('Saved','Offer saved.','success');}catch(e){handleErr(e)}}
async function saveReward(e){e.preventDefault();if(!requirePerm('rewards.write'))return;const id=el('rewardEditId').value||null;const data={title:el('rewardEditTitle').value.trim(),category:el('rewardEditCategory').value.trim(),icon:el('rewardEditIcon').value.trim(),price:Number(el('rewardEditPrice').value||0),stock:Number(el('rewardEditStock').value||0),type:el('rewardEditType').value.trim(),active:el('rewardEditActive').checked,updatedAt:ts()};try{if(id)await db.collection('rewards').doc(id).update(data);else{data.createdAt=ts();data.ts=now();await db.collection('rewards').add(data)}closeAdminModal('rewardEditorModal');await audit(id?'reward_update':'reward_create',data.title);await refreshAll();toast('Saved','Reward saved.','success');}catch(e){handleErr(e)}}
async function saveSettings(e){e?.preventDefault();if(!requirePerm('settings.write'))return;const s={...ADMIN.data.settings,coinRate:Number(el('setCoinRate').value||10000),signupBonus:Number(el('setSignupBonus').value||0),minWithdraw:Number(el('setMinWithdraw').value||10000),withdrawalFeePct:Number(el('setWithdrawFee').value||0),maintenance:!!el('setMaintenance')?.checked,allowSignups:el('setAllowSignups')?el('setAllowSignups').checked:(ADMIN.data.settings?.allowSignups!==false),siteUrl:el('setSiteUrl').value.trim(),supportEmail:el('setSupportEmail').value.trim(),announcement:el('setAnnouncement').value.trim(),updatedAt:ts()};try{await db.collection('settings').doc('global').set(s,{merge:true});ADMIN.data.settings=s;await audit('settings_update','global');toast('Saved','Settings updated.','success');await refreshAll();}catch(e){handleErr(e)}}
async function saveAds(e){e?.preventDefault();if(!requirePerm('ads.write'))return;const cur=ADMIN.data.settings||{},ads={...(cur.ads||{}),adsterra:{enabled:!!el('adNetworkAdsterra')?.checked},monetag:{enabled:!!el('adNetworkMonetag')?.checked},hilltop:{enabled:!!el('adNetworkHilltop')?.checked},popads:{enabled:!!el('adNetworkPopads')?.checked},placements:{banner:!!el('adPlacementBanner')?.checked,native:!!el('adPlacementNative')?.checked,popunder:!!el('adPlacementPopunder')?.checked,socialbar:!!el('adPlacementSocialbar')?.checked,smartlink:!!el('adPlacementSmartlink')?.checked,monetagDirect:!!el('adPlacementMonetagDirect')?.checked}};const patch={ads,adReward:Number(el('adsCoinsPerAd').value||120),adDailyCap:Number(el('adsDailyCap').value||15),adECPM:Number(el('adsECPM').value||0),adMode:el('adTestMode')?.checked?'test':'production',updatedAt:ts()};try{await db.collection('settings').doc('global').set(patch,{merge:true});await audit('ads_update',JSON.stringify(ads));toast('Saved','Ad control center updated.','success');await refreshAll();}catch(e){handleErr(e)}}
async function deleteDoc(colName,id){if(!requirePerm(colName+'.delete')&&!requirePerm(colName+'.write'))return;const ok=await modalConfirm('Delete','Delete this record?','Delete');if(!ok)return;try{await db.collection(colName).doc(id).delete();await audit('delete_'+colName,id);await refreshAll();toast('Deleted','Record deleted.','success');}catch(e){handleErr(e)}}
async function completeOrder(id,refund=false){if(!requirePerm('orders.write'))return;const o=await get('orders',id);if(!o)return;try{if(refund){await db.collection('orders').doc(id).update({status:'refunded',refundedAt:ts()});if(o.uid&&Number(o.cost||0)>0)await db.collection('users').doc(o.uid).update({balance:inc(Number(o.cost||0)),lifetimeSpent:inc(-Number(o.cost||0))});}else await db.collection('orders').doc(id).update({status:'completed',completedAt:ts()});await audit(refund?'order_refund':'order_complete',id);await refreshAll();toast('Order','Order updated.','success');}catch(e){handleErr(e)}}
async function updateWd(id,status){if(!requirePerm('withdrawals.process'))return;const w=await get('withdrawals',id);if(!w)return;try{const ref=db.collection('withdrawals').doc(id);const u=w.uid?db.collection('users').doc(w.uid):null;const lock=w.uid?db.collection('withdrawal_locks').doc(w.uid):null;const batch=db.batch();batch.update(ref,{status,updatedAt:ts(),...(status==='paid'?{paidAt:ts()}:status==='rejected'?{rejectionReason:'Rejected by admin',rejectedAt:ts()}:{approvedAt:ts()})});if(status==='paid'&&u)batch.update(u,{lockedBalance:inc(-Number(w.amount||0)),pendingWithdrawal:inc(-Number(w.amount||0)),totalWithdrawn:inc(Number(w.receive||w.amount||0))});if(status==='rejected'&&u)batch.update(u,{balance:inc(Number(w.amount||0)),lockedBalance:inc(-Number(w.amount||0)),pendingWithdrawal:inc(-Number(w.amount||0))});if(lock&&['paid','rejected'].includes(status))batch.delete(lock);await batch.commit();await audit('withdrawal_'+status,id);await refreshAll();toast('Withdrawal','Withdrawal updated.','success');}catch(e){handleErr(e)}}
async function resolveTicket(id){if(!requirePerm('tickets.write'))return;try{await db.collection('tickets').doc(id).update({status:'resolved',resolvedAt:ts(),resolvedBy:ADMIN.user.uid});const t=await get('tickets',id);if(t?.uid)await db.collection('notifications').add({uid:t.uid,title:'Ticket resolved',body:t.subject||'Your support ticket was resolved.',read:false,ts:now(),createdAt:ts()});await audit('ticket_resolve',id);await refreshAll();toast('Support','Ticket resolved.','success');}catch(e){handleErr(e)}}
async function saveContentSettings(e){e?.preventDefault();if(!requirePerm('content.write'))return;const patch={heroTitle:el('contentHeroTitle').value,heroSub:el('contentHeroSub').value,banner:el('contentBanner').value,terms:el('termsEditor').innerHTML,privacy:el('privacyEditor').innerHTML,updatedAt:ts()};try{await db.collection('settings').doc('global').set(patch,{merge:true});await audit('content_update','settings');await refreshAll();toast('Content','Content saved.','success');}catch(e){handleErr(e)}}
async function saveReferral(e){e?.preventDefault();if(!requirePerm('referral.write'))return;const patch={referralPercent:Number(el('refPercent').value||10),referralJoinBonus:Number(el('refJoinBonus').value||0),refActivityBonus:Number(el('refActivityBonus').value||0),offerBonus:Number(el('refOfferBonus').value||0),updatedAt:ts()};try{await db.collection('settings').doc('global').set(patch,{merge:true});await refreshAll();toast('Referral','Referral settings saved.','success');}catch(e){handleErr(e)}}
async function saveSecurity(e){e?.preventDefault();if(!requirePerm('security.write'))return;const patch={wdDayCap:Number(el('setWdDay').value||0),wdWeekCap:Number(el('setWdWeek').value||0),topupDayCap:Number(el('setTopupDay').value||0),maxWithdraw:Number(el('setWdMax').value||0),vpnPenalty:Number(el('setVpnPenalty').value||0),emuPenalty:Number(el('setEmuPenalty').value||0),dupPenalty:Number(el('setDupPenalty').value||0),flagThreshold:Number(el('setFlagThreshold').value||50),restrictThreshold:Number(el('setRestrictThreshold').value||75),banThreshold:Number(el('setBanThreshold').value||90),updatedAt:ts()};try{await db.collection('settings').doc('global').set(patch,{merge:true});await audit('security_update','settings');await refreshAll();toast('Security','Security settings saved.','success');}catch(e){handleErr(e)}}
async function addFaq(){if(!requirePerm('content.write'))return;const q=prompt('Question');if(!q)return;const a=prompt('Answer');if(!a)return;try{await db.collection('faqs').add({q,a,createdAt:ts(),ts:now()});await audit('faq_create',q);await refreshAll();toast('FAQ','FAQ added.','success');}catch(e){handleErr(e)}}
async function addPost(){if(!requirePerm('content.write'))return;const title=prompt('Post title');if(!title)return;const content=prompt('Post content');if(content==null)return;try{await db.collection('posts').add({title,content,createdAt:ts(),ts:now(),active:true});await refreshAll();toast('Blog','Post added.','success');}catch(e){handleErr(e)}}
async function createCampaign(){if(!requirePerm('content.write'))return;const type=(prompt('Campaign type: promo, event or post','promo')||'').trim().toLowerCase();if(!['promo','event','post'].includes(type))return toast('Campaign','Choose promo, event or post.','warning');if(type==='promo'){const code=(prompt('Promo code')||'').trim().toUpperCase();if(!code)return;const reward=Number(prompt('Reward coins','100')||0);if(!reward)return;await db.collection('promos').add({code,reward,title:code,active:true,createdAt:ts(),ts:now()});}else if(type==='event'){const title=(prompt('Event title')||'').trim();if(!title)return;await db.collection('events').add({title,subtitle:prompt('Subtitle')||'',status:'active',active:true,createdAt:ts(),ts:now()});}else{const title=(prompt('Post title')||'').trim();if(!title)return;await db.collection('posts').add({title,content:prompt('Post content')||'',active:true,createdAt:ts(),ts:now()});}await audit('campaign_create',type);await refreshAll();toast('Campaign','Campaign created.','success')}
async function seedData(){if(!requirePerm('settings.write'))return;const offers=[{title:'Starter Offer',provider:'AdGate',payout:250,minutes:3,description:'Complete a partner offer.',link:'#',active:true,category:'general'},{title:'Gaming Offer',provider:'Lootably',payout:500,minutes:10,description:'Reach a milestone.',link:'#',active:true,category:'games'}];const games=[{title:'Free Fire',platform:'Android',link:'#',description:'Game milestone offers',icon:'🔥',active:true},{title:'Roblox',platform:'All',link:'#',description:'Game milestone offers',icon:'🧱',active:true}];const surveys=[{title:'Quick Opinion',payout:120,minutes:5,link:'#',description:'5 minute survey',active:true}];const rewards=[{title:'PayPal $1',price:10000,stock:50,category:'cash',icon:'💵',type:'reward',active:true},{title:'400 Robux',price:18000,stock:25,category:'games',icon:'🎮',type:'reward',active:true}];const promos=[{code:'WELCOME2026',title:'Welcome Bonus',reward:500,active:true}];try{for(const x of offers)await db.collection('offers').add({...x,createdAt:ts(),ts:now()});for(const x of games)await db.collection('games').add({...x,createdAt:ts(),ts:now()});for(const x of surveys)await db.collection('surveys').add({...x,createdAt:ts(),ts:now()});for(const x of rewards)await db.collection('rewards').add({...x,createdAt:ts(),ts:now(),initialStock:x.stock});for(const x of promos)await db.collection('promos').add({...x,createdAt:ts(),ts:now()});await db.collection('settings').doc('global').set({...DEFAULT,updatedAt:ts()},{merge:true});await audit('seed_data','initial');await refreshAll();toast('Seed','Sample data created.','success');}catch(e){handleErr(e)}}
async function exportBackup(){downloadJSON('rewords-backup',ADMIN.data);await audit('backup_export','full');}
function importBackup(){const i=document.createElement('input');i.type='file';i.accept='application/json';i.onchange=async()=>{const file=i.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!await modalConfirm('Import backup','This will write records into Firestore. Continue?','Import'))return;for(const [collection,rows] of Object.entries(data)){if(collection==='settings'){if(rows)await db.collection('settings').doc('global').set(rows,{merge:true});continue}if(!Array.isArray(rows)||!['users','offers','games','surveys','rewards','providers','promos','events','posts','faqs'].includes(collection))continue;for(const row of rows){const id=row.id;const copy={...row};delete copy.id;await db.collection(collection).doc(id||undefined).set(copy,{merge:true});}}await audit('backup_import','full');await refreshAll();toast('Import','Backup imported.','success');}catch(e){handleErr(e,'Invalid backup file')}};i.click();}
async function grantAdmin(e){e.preventDefault();if(!requirePerm('admins.manage'))return;const email=el('grantAdminEmail').value.trim().toLowerCase(),role=el('grantAdminRole').value;const q=await auth.fetchSignInMethodsForEmail(email).catch(()=>[]);if(!q.length){toast('Admin','User must create a Firebase Auth account first.','warning');return}const users=ADMIN.data.users||[];const target=users.find(u=String(u.email||'').toLowerCase()===email);if(!target){toast('Admin','Create/sign in the user first.','warning');return}const perms=role==='super'?['*']:role==='finance'?['users.read','finance.read','withdrawals.process','orders.write','logs.write']:['users.read','tickets.write','content.write','ads.write','offers.write','rewards.write'];await db.collection('admin_users').doc(target.id).set({email,uid:target.id,role,permissions:perms,active:true,grantedBy:ADMIN.user.uid,createdAt:ts(),ts:now()},{merge:true});await audit('grant_admin',email);toast('Admin','Admin access granted.','success');await renderRoles();}
async function revokeAdmin(id){if(!requirePerm('admins.manage'))return;const row=await get('admin_users',id);if(!row)return;if(row.uid===ADMIN.user.uid)return toast('Admin','You cannot revoke your own access.','warning');const ok=await modalConfirm('Revoke admin','Revoke this admin?','Revoke');if(!ok)return;await db.collection('admin_users').doc(id).update({active:false,revokedAt:ts(),revokedBy:ADMIN.user.uid});await audit('revoke_admin',id);await renderRoles();}
async function viewUser(id){const u=await get('users',id);if(!u)return;openAdminModal('User details',`<div class="grid grid-2 gap-2">${Object.entries(u).filter(([k])=>k!=='id').slice(0,20).map(([k,v])=>`<div class="card"><b>${esc(k)}</b><div>${esc(typeof v==='object'?JSON.stringify(v):v)}</div></div>`).join('')}</div>`);}
async function viewTicket(id){const t=await get('tickets',id);if(!t)return;openAdminModal('Ticket',`<div><h3>${esc(t.subject||'Ticket')}</h3><p>${esc(t.body||'')}</p><div>Status: ${esc(t.status||'open')}</div></div>`);}
function bindAdmin(){
  el('adminLoginForm')?.addEventListener('submit',login);el('adminLogoutBtn')?.addEventListener('click',logout);el('toggleAdminPw')?.addEventListener('click',()=>{const i=el('adminPassword');i.type=i.type==='password'?'text':'password';});el('adminRefreshBtn')?.addEventListener('click',refreshAll);el('adminThemeToggle')?.addEventListener('click',()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark');el('collapseSideBtn')?.addEventListener('click',()=>document.body.classList.toggle('admin-collapsed'));el('openSideBtn')?.addEventListener('click',()=>document.body.classList.toggle('admin-mobile-open'));
  $$('[data-admin-nav]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();nav(a.dataset.adminNav);}));
  el('createOfferBtn')?.addEventListener('click',()=>openOfferEditor());el('createCampaignBtn')?.addEventListener('click',createCampaign);el('saveAdsCenterBtn')?.addEventListener('click',saveAds);el('createRewardBtn')?.addEventListener('click',()=>openRewardEditor());el('createGameBtn')?.addEventListener('click',()=>genericEditor('game'));el('createSurveyBtn')?.addEventListener('click',()=>genericEditor('survey'));el('createProviderBtn')?.addEventListener('click',()=>genericEditor('provider'));
  el('offerEditorForm')?.addEventListener('submit',saveOffer);el('rewardEditorForm')?.addEventListener('submit',saveReward);el('adsConfigForm')?.addEventListener('submit',saveAds);el('coinEconomyForm')?.addEventListener('submit',saveSettings);el('siteControlsForm')?.addEventListener('submit',saveSettings);el('saveAllSettingsBtn')?.addEventListener('click',saveSettings);el('referralSettingsForm')?.addEventListener('submit',saveReferral);el('contentSettingsForm')?.addEventListener('submit',saveContentSettings);el('saveTermsBtn')?.addEventListener('click',saveContentSettings);el('savePrivacyBtn')?.addEventListener('click',saveContentSettings);el('authSettingsForm')?.addEventListener('submit',e=>{e.preventDefault();toast('Auth','Firebase Auth settings are managed in Firebase Console; no fake client setting is saved.','info')});el('rateLimitsForm')?.addEventListener('submit',saveSecurity);el('riskEngineForm')?.addEventListener('submit',saveSecurity);el('saveSecurityBtn')?.addEventListener('click',saveSecurity);el('grantAdminForm')?.addEventListener('submit',grantAdmin);el('revokeAdminForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=el('revokeAdminEmail').value.trim().toLowerCase();const rows=await col('admin_users');const x=rows.find(r=>String(r.email||'').toLowerCase()===email);if(x)await revokeAdmin(x.id);else toast('Admin','Admin not found.','warning');});el('addFaqBtn')?.addEventListener('click',addFaq);el('addPostBtn')?.addEventListener('click',addPost);el('seedDataBtn')?.addEventListener('click',seedData);el('exportBackupBtn')?.addEventListener('click',exportBackup);el('importBackupBtn')?.addEventListener('click',importBackup);el('exportUsersBtn')?.addEventListener('click',()=>csv('users',[['username','email','balance','status'],...(ADMIN.data.users||[]).map(x=>[x.username,x.email,x.balance,x.status])]));el('exportOrdersBtn')?.addEventListener('click',()=>csv('orders',[['id','uid','type','cost','status'],...(ADMIN.data.orders||[]).map(x=>[x.id,x.uid,x.type,x.cost,x.status])]));el('exportWithdrawalsBtn')?.addEventListener('click',()=>csv('withdrawals',[['id','uid','amount','method','status'],...(ADMIN.data.withdrawals||[]).map(x=>[x.id,x.uid,x.amount,x.method,x.status])]));el('exportTicketsBtn')?.addEventListener('click',()=>csv('tickets',[['id','uid','subject','status'],...(ADMIN.data.tickets||[]).map(x=>[x.id,x.uid,x.subject,x.status])]));el('exportLogsBtn')?.addEventListener('click',()=>csv('logs',[['action','admin','details'],...(ADMIN.data.admin_logs||[]).map(x=>[x.action,x.adminEmail,x.details])]));el('checkClaimBtn')?.addEventListener('click',async()=>{const email=el('checkClaimEmail').value.trim().toLowerCase();const rows=await col('admin_users');const x=rows.find(r=>String(r.email||'').toLowerCase()===email);setText('checkClaimResult',x?`${x.role} · ${x.active===false?'inactive':'active'}`:'No admin record');});
  el('sideSearchInput')?.addEventListener('input',()=>{const q=el('sideSearchInput').value.toLowerCase();$$('[data-admin-nav]').forEach(n=>n.style.display=n.textContent.toLowerCase().includes(q)?'flex':'');});el('topbarSearch')?.addEventListener('input',()=>{const q=el('topbarSearch').value.toLowerCase();if(q){if((ADMIN.data.users||[]).some(x=>JSON.stringify(x).toLowerCase().includes(q)))nav('users');else if((ADMIN.data.offers||[]).some(x=>JSON.stringify(x).toLowerCase().includes(q)))nav('offers');}});
  el('usersSearch')?.addEventListener('input',renderUsers);el('offersSearch')?.addEventListener('input',renderOffers);el('rewardsSearch')?.addEventListener('input',renderRewards);
  el('ledgerFilterTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-ledger-filter]');if(!b)return;ADMIN.ledgerFilter=b.dataset.ledgerFilter;$$('#ledgerFilterTabs [data-ledger-filter]').forEach(x=>x.classList.toggle('active',x===b));renderFinance();});
  el('contentTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-content-tab]');if(!b)return;$$('#contentTabs [data-content-tab]').forEach(x=>x.classList.toggle('active',x===b));const map={faq:'contentFaqWrap',legal:'contentLegalWrap',settings:'contentSettingsWrap',blog:'contentBlogWrap'};Object.values(map).forEach(id=>el(id)?.classList.add('hidden'));el(map[b.dataset.contentTab])?.classList.remove('hidden');});
  el('analyticsRangeTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-analytics-range]');if(!b)return;$$('#analyticsRangeTabs [data-analytics-range]').forEach(x=>x.classList.toggle('active',x===b));renderAnalytics();});
  el('fraudTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-fraud-tab]');if(!b)return;$$('#fraudTabs [data-fraud-tab]').forEach(x=>x.classList.toggle('active',x===b));const map={flagged:'fraudFlaggedWrap',blacklist:'fraudBlacklistWrap',duplicates:'fraudDuplicatesWrap',events:'fraudEventsWrap'};Object.values(map).forEach(id=>el(id)?.classList.add('hidden'));el(map[b.dataset.fraudTab])?.classList.remove('hidden');});
  $$('#admin-orders .filter-chip[data-order-type]').forEach(b=>b.addEventListener('click',()=>{ADMIN.orderFilter=b.dataset.orderType;$$('#admin-orders .filter-chip[data-order-type]').forEach(x=>x.classList.toggle('active',x===b));renderOrders();}));
  $$('[data-rte]').forEach(b=>b.addEventListener('click',()=>{const editor=b.closest('.card')?.querySelector('.rte-area');if(!editor)return;editor.focus();const cmd=b.dataset.rte;if(cmd==='bold'||cmd==='italic')document.execCommand(cmd,false);else if(cmd==='h2')document.execCommand('formatBlock',false,'h2');else if(cmd==='ul')document.execCommand('insertUnorderedList',false);}));
  document.addEventListener('click',async e=>{
    const a=e.target.closest('[data-admin-action]');
    if(a){
      const act=a.dataset.adminAction,id=a.dataset.id;
      try{
        if(act==='viewUser') await viewUser(id);
        else if(act==='editOffer') openOfferEditor(id);
        else if(act==='editReward') openRewardEditor(id);
        else if(act==='editGame') genericEditor('game',id);
        else if(act==='editSurvey') genericEditor('survey',id);
        else if(act==='editProvider') genericEditor('provider',id);
        else if(act==='delete') await deleteDoc(a.dataset.col,id);
        else if(act==='completeOrder') await completeOrder(id);
        else if(act==='refundOrder') await completeOrder(id,true);
        else if(act==='approveWd') await updateWd(id,'approved');
        else if(act==='payWd') await updateWd(id,'paid');
        else if(act==='rejectWd') await updateWd(id,'rejected');
        else if(act==='resolveTicket') await resolveTicket(id);
        else if(act==='viewTicket') await viewTicket(id);
        else if(act==='revokeAdmin') await revokeAdmin(id);
      }catch(err){handleErr(err)}
    }
    const gs=e.target.closest('[data-generic-save]');
    if(gs) await saveGeneric(gs.dataset.genericSave,gs.dataset.id||null);
  });
  $$('[onclick^="closeAdminModal"]').forEach(b=>b.addEventListener('click',()=>{}));
  el('adminConfirmCancel')?.addEventListener('click',()=>closeAdminModal('adminConfirmDialog'));el('adminConfirmOk')?.addEventListener('click',()=>closeAdminModal('adminConfirmDialog'));
  $$('.modal-close').forEach(b=>b.addEventListener('click',()=>b.closest('.modal-scrim')?.classList.remove('open')));
}
function boot(){document.documentElement.dataset.theme='dark';bindAdmin();initAuth();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.closeAdminModal=closeAdminModal;window.openAdminModal=openAdminModal;
