const firebaseConfig={
  "apiKey": "AIzaSyBPMbRdVEJ85Is7eg4UkAFs_UHq-BD_Fhg",
  "authDomain": "rewords-45ccf.firebaseapp.com",
  "projectId": "rewords-45ccf",
  "storageBucket": "rewords-45ccf.firebasestorage.app",
  "messagingSenderId": "324257034049",
  "appId": "1:324257034049:web:2e75279382793007683bc0",
  "measurementId": "G-5LNDESBVST"
};firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();const $=id=>document.getElementById(id);function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)};async function admin(u){const c=(await u.getIdTokenResult(true)).claims||{};return c.admin===true||c.role==='admin'}auth.onAuthStateChanged(async u=>{if(!u){$('gate').classList.remove('hidden');$('dash').classList.add('hidden');return}try{if(!await admin(u))throw Error('الحساب ليس Admin');$('gate').classList.add('hidden');$('dash').classList.remove('hidden');loadAll()}catch(e){toast(e.message);auth.signOut()}});$('login').onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword($('email').value.trim(),$('pass').value)}catch(x){toast(x.message)}};$('logout').onclick=()=>auth.signOut();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
async function loadAll(){await Promise.all([stats(),users(),orders(),ads(),settings(),maintenance()])}
async function stats(){const u=(await db.collection('users').limit(500).get()).docs.length,o=(await db.collection('orders').limit(500).get()).docs.length;$('stats').innerHTML='<div class="stat-card"><span>المستخدمون</span><strong>'+u+'</strong></div><div class="stat-card"><span>الطلبات</span><strong>'+o+'</strong></div>'}
async function users(){const s=await db.collection('users').limit(500).get();$('usersTable').innerHTML='<table class="table"><tr><th>المستخدم</th><th>الرصيد</th><th>الحالة</th></tr>'+s.docs.map(d=>{const x=d.data();return '<tr><td>'+esc(x.name)+'<br>'+esc(x.email)+'</td><td>'+Number(x.balanceUsd||0).toFixed(2)+'</td><td>'+esc(x.accountStatus||'active')+'</td></tr>'}).join('')+'</table>'}
async function orders(){const s=await db.collection('orders').limit(500).get();$('ordersTable').innerHTML='<table class="table"><tr><th>النوع</th><th>المبلغ</th><th>الحالة</th></tr>'+s.docs.map(d=>{const x=d.data();return '<tr><td>'+esc(x.type)+'</td><td>'+Number(x.amountUsd||0).toFixed(2)+'</td><td>'+esc(x.status)+'</td></tr>'}).join('')+'</table>'}
const placements=['adsterra-468','adsterra-native','adsterra-popunder','adsterra-smartlink','adsterra-socialbar','monetag-multitag','monetag-direct','hilltop-popunder'];
async function ads(){const s=await db.collection('ads').get(),m={};s.forEach(d=>m[d.id]=d.data());$('adsTable').innerHTML='<table class="table"><tr><th>Placement</th><th>الحالة</th><th>إجراء</th></tr>'+placements.map(id=>{const on=m[id]?.enabled!==false;return '<tr><td>'+esc(id)+'</td><td>'+(on?'مفعّل':'متوقف')+'</td><td><button class="btn ghost" data-ad="'+id+'">'+(on?'إيقاف':'تفعيل')+'</button></td></tr>'}).join('')+'</table>';document.querySelectorAll('[data-ad]').forEach(b=>b.onclick=async()=>{await db.collection('ads').doc(b.dataset.ad).set({enabled:m[b.dataset.ad]?.enabled===false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});ads()})}
async function settings(){const s=await db.collection('settings').doc('public').get();$('usdMad').value=s.exists?Number(s.data()?.currency?.USD_MAD||10):10}
$('settingsForm').onsubmit=async e=>{e.preventDefault();await db.collection('settings').doc('public').set({currency:{USD_MAD:Number($('usdMad').value)},updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});toast('تم الحفظ')};
async function maintenance(){const s=await db.collection('maintenance').doc('state').get(),x=s.exists?s.data():{};$('maintEnabled').checked=!!x.enabled;$('maintTitle').value=x.title||'';$('maintDescription').value=x.description||'';$('maintReturn').value=x.estimatedReturn||''}
$('maintForm').onsubmit=async e=>{e.preventDefault();await db.collection('maintenance').doc('state').set({enabled:$('maintEnabled').checked,title:$('maintTitle').value,description:$('maintDescription').value,estimatedReturn:$('maintReturn').value,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});toast('تم الحفظ')};
async function exportCol(c){const s=await db.collection(c).limit(5000).get(),a=s.docs.map(d=>({id:d.id,...d.data()}));const b=new Blob([JSON.stringify(a,(k,v)=>v?.toDate?v.toDate().toISOString():v,2)],{type:'application/json'}),u=URL.createObjectURL(b),x=document.createElement('a');x.href=u;x.download='rewords-'+c+'.json';x.click();URL.revokeObjectURL(u)}$('exportUsers').onclick=()=>exportCol('users');$('exportOrders').onclick=()=>exportCol('orders');function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}