/* REWORDS APP — rewritten from scratch against index.html/style.css. */
{firebase}

const db = firebase.firestore();
const auth = firebase.auth();
const ts = () => firebase.firestore.FieldValue.serverTimestamp();
const inc = (n) => firebase.firestore.FieldValue.increment(Number(n)||0);
const now = () => Date.now();
const todayKey = () => new Date().toISOString().slice(0,10);
const yesterdayKey = () => new Date(Date.now()-86400000).toISOString().slice(0,10);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2)+Date.now().toString(36);
const esc = (v) => String(v ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const fmt = (v) => Number(v||0).toLocaleString('en-US');
const el = id => document.getElementById(id);
const $$ = s => Array.from(document.querySelectorAll(s));

const State = {
  user:null, profile:null, settings:{},
  offers:[], games:[], surveys:[], rewards:[], providers:[], faqs:[], events:[], promos:[], posts:[],
  notifications:[], ledger:[], tickets:[], referrals:[], leaderboard:[],
  lang:localStorage.getItem('rewords_lang')||'ar', theme:localStorage.getItem('rewords_theme')||'dark', currentPage:'home',
  selectedTopupGame:null, selectedTopupPackage:null, selectedWdMethod:'PayPal', authBusy:false
};

const DEFAULT_SETTINGS = {
  coinRate:10000, minWithdraw:10000, signupBonus:100, adReward:120, adDailyCap:15,
  withdrawalFeePct:1, referralPercent:10, referralJoinBonus:0, offerBonusPercent:100,
  maintenance:false, allowSignups:true, supportEmail:'support@rewords.com', siteUrl:location.origin,
  announcement:'', adMode:'production',
  ads:{
    adsterra:{enabled:true}, monetag:{enabled:true}, hilltop:{enabled:true}, popads:{enabled:false},
    placements:{banner:true,native:true,popunder:true,socialbar:true,smartlink:true,monetagDirect:true}
  }
};
const PAGES = ['home','earn','offers','games','surveys','watch','daily','tasks','challenges','checkin','streaks','referral','leaderboard','rewards','topup','withdraw','transactions','notifications','support','profile','security','faq','terms','privacy','antifraud','wallet','promo','events','blog','article','history','offlinerewards','more'];
const AUTH_REQUIRED = new Set(['wallet','withdraw','topup','transactions','notifications','profile','security','referral','history','checkin','streaks','challenges','tasks','daily','watch','offlinerewards']);
const DAILY_PLAN=[50,100,200,350,500,750,1000];
const FIXED_DAILY_GAMES={scratch:100,mystery:200,treasure:300};

const I18N_EN = {
  'nav.home':'Home','nav.earn':'Earn','nav.offers':'Offers','nav.games':'Games','nav.surveys':'Surveys','nav.watch':'Watch Ads','nav.daily':'Daily','nav.rewards':'Rewards','nav.referral':'Referral','nav.leaderboard':'Leaderboard','nav.support':'Support','nav.tasks':'Tasks','nav.challenges':'Challenges','nav.streaks':'Streaks','nav.topup':'Top Up','nav.withdraw':'Withdraw','nav.transactions':'Transactions','nav.wallet':'Wallet','nav.notifications':'Notifications','nav.profile':'Profile','nav.security':'Security','nav.faq':'FAQ','nav.terms':'Terms','nav.privacy':'Privacy','nav.antifraud':'Status','nav.promo':'Promo Codes','nav.events':'Events','nav.blog':'News','nav.more':'More','nav.history':'History','nav.offlinerewards':'Offline Rewards',
  'auth.login':'Login','auth.logout':'Log Out','auth.signup':'Create Account','auth.needLogin':'Sign in to unlock all features and start earning.',
  'home.heroTitle':'Earn Coins Doing What You Love','home.heroSub':'Play games, complete offers, take surveys and watch rewarded ads.','home.startEarning':'Start Earning','home.dailyReward':'Daily Reward','home.browseRewards':'Browse Rewards','home.claimNow':'Claim Now','home.seeAll':'See All','home.popularRewards':'Popular Rewards','home.topOffers':'Top Earning Offers','home.topGames':'Top Earning Games','home.bestSurveys':'Best Surveys','home.topUsers':'Best Users Today','home.recentlyCompleted':'Recently Completed','home.faqTitle':'Frequently Asked Questions',
  'offers.none':'No offers available','offers.noneSub':'Open the Admin Panel → System Settings → Seed Sample Data.','games.none':'No games available','games.noneSub':'Seed data from the Admin Panel.','surveys.none':'No surveys available','rewards.none':'No rewards available','events.none':'No events right now','blog.none':'No articles yet','promo.none':'No promo codes',
  'popup.confirm':'Confirm','popup.cancel':'Cancel','popup.rewardTitle':'Reward Earned!','popup.awesome':'Awesome!',
  'err.fillAll':'Please fill in all fields','err.insufficient':'Insufficient coins','err.username':'Username must be at least 3 characters','err.password':'Password must be at least 8 characters',
  'ledger.signupBonus':'Welcome signup bonus','ledger.offerComplete':'Offer completed: {n}','ledger.surveyComplete':'Survey completed: {n}','ledger.rewardRedeem':'Reward redeemed: {n}','ledger.adReward':'Rewarded ad','ledger.adBonus':'Daily ad bonus','ledger.interstitial':'Interstitial ad reward','ledger.dailyClaim':'Daily claim · Day {n}','ledger.wheel':'Spin wheel bonus','ledger.scratch':'Scratch card bonus','ledger.mystery':'Mystery box reward','ledger.treasure':'Treasure chest reward','ledger.topup':'Game top-up: {g}','ledger.withdrawal':'Withdrawal','ledger.promo':'Promo code: {n}',
  'watch.capReached':'Daily ad cap reached. Come back tomorrow!','daily.claimed':'Claimed for today','daily.wheelSpun':'Wheel already spun today','daily.scratchDone':'Scratch card used for today','daily.mysteryDone':'Box opened for today','daily.treasureDone':'Treasure collected for today',
  'withdraw.tooSmall':'Minimum withdrawal is {n} coins','withdraw.pendingExists':'You already have a pending withdrawal.','withdraw.requested':'Withdrawal requested','withdraw.requestedSub':'We will review it within 24-72 hours.',
  'topup.success':'Top-up order placed!','topup.selectGameFirst':'Select a game first','topup.enterPlayerId':'Enter your player ID',
  'rewards.ordered':'Order placed! You will receive it within 24 hours.','rewards.confirm':'Confirm Redemption',
  'promo.invalid':'Invalid promo code','promo.used':'This code was already used.',
  'referral.copied':'Link copied to clipboard!','referral.self':'You cannot use your own code!','referral.already':'You already have a referrer.','referral.applied':'Referral code applied!',
  'support.sent':'Ticket sent','profile.saved':'Profile updated successfully!','transactions.none':'No transactions yet','transactions.noneSub':'Start earning to see your history.','notifications.none':'No notifications'
}; 
const I18N_AR = {
  'nav.home':'الرئيسية','nav.earn':'اكسب','nav.offers':'العروض','nav.games':'الألعاب','nav.surveys':'الاستبيانات','nav.watch':'شاهد الإعلانات','nav.daily':'المكافآت اليومية','nav.rewards':'المكافآت','nav.referral':'الإحالة','nav.leaderboard':'المتقدمون','nav.support':'الدعم','nav.tasks':'المهام','nav.challenges':'التحديات','nav.streaks':'التتابع','nav.topup':'شحن الألعاب','nav.withdraw':'السحب','nav.transactions':'المعاملات','nav.wallet':'المحفظة','nav.notifications':'الإشعارات','nav.profile':'الملف الشخصي','nav.security':'الأمان','nav.faq':'الأسئلة','nav.terms':'الشروط','nav.privacy':'الخصوصية','nav.antifraud':'الحالة','nav.promo':'أكواد الخصم','nav.events':'الفعاليات','nav.blog':'الأخبار','nav.more':'المزيد','nav.history':'السجل','nav.offlinerewards':'مكافآت دون اتصال',
  'auth.login':'تسجيل الدخول','auth.logout':'تسجيل الخروج','auth.signup':'إنشاء حساب','auth.needLogin':'سجّل الدخول لتفعيل جميع الميزات والبدء في الربح.',
  'home.heroTitle':'اربح عملات بفعل ما تحب','home.heroSub':'العب الألعاب، أكمل العروض، أجب عن الاستبيانات وشاهد الإعلانات المدفوعة.','home.startEarning':'ابدأ الربح','home.dailyReward':'المكافأة اليومية','home.browseRewards':'تصفح المكافآت','home.claimNow':'استلم الآن','home.seeAll':'عرض الكل','home.popularRewards':'المكافآت الشائعة','home.topOffers':'أعلى العروض ربحًا','home.topGames':'أعلى الألعاب ربحًا','home.bestSurveys':'أفضل الاستبيانات','home.topUsers':'أفضل المستخدمين اليوم','home.recentlyCompleted':'المكتمل حديثًا','home.faqTitle':'الأسئلة الشائعة',
  'offers.none':'لا توجد عروض متاحة','offers.noneSub':'افتح لوحة الأدمن → System Settings → Seed Sample Data.','games.none':'لا توجد ألعاب متاحة','games.noneSub':'أضف البيانات من لوحة الأدمن.','surveys.none':'لا توجد استبيانات متاحة','rewards.none':'لا توجد مكافآت متاحة','events.none':'لا توجد فعاليات حاليًا','blog.none':'لا توجد مقالات بعد','promo.none':'لا توجد أكواد',
  'popup.confirm':'تأكيد','popup.cancel':'إلغاء','popup.rewardTitle':'مكافأة ربحتها!','popup.awesome':'رائع!',
  'err.fillAll':'يرجى ملء جميع الحقول','err.insufficient':'عملات غير كافية','err.username':'اسم المستخدم 3 أحرف على الأقل','err.password':'كلمة المرور 8 أحرف على الأقل',
  'ledger.signupBonus':'مكافأة التسجيل الترحيبية','ledger.offerComplete':'اكتمل العرض: {n}','ledger.surveyComplete':'اكتمل الاستبيان: {n}','ledger.rewardRedeem':'تم استبدال: {n}','ledger.adReward':'إعلان مكافأة','ledger.adBonus':'مكافأة الإعلان اليومية','ledger.interstitial':'مكافأة إعلان بيني','ledger.dailyClaim':'مطالبة يومية · يوم {n}','ledger.wheel':'مكافأة العجلة','ledger.scratch':'مكافأة بطاقة الخدش','ledger.mystery':'مكافأة الصندوق الغامض','ledger.treasure':'مكافأة الكنز','ledger.topup':'شحن لعبة: {g}','ledger.withdrawal':'سحب','ledger.promo':'كود خصم: {n}',
  'watch.capReached':'تم الوصول للحد اليومي. عد غدًا!','daily.claimed':'تم الاستلام لليوم','daily.wheelSpun':'تم التدوير اليوم','daily.scratchDone':'استُخدمت البطاقة اليوم','daily.mysteryDone':'فُتح الصندوق اليوم','daily.treasureDone':'جُمع الكنز اليوم',
  'withdraw.tooSmall':'الحد الأدنى للسحب {n} عملة','withdraw.pendingExists':'لديك سحب قيد المراجعة بالفعل.','withdraw.requested':'تم طلب السحب','withdraw.requestedSub':'سنراجعه خلال 24-72 ساعة.',
  'topup.success':'تم تقديم طلب الشحن!','topup.selectGameFirst':'اختر اللعبة أولاً','topup.enterPlayerId':'أدخل معرف اللاعب',
  'rewards.ordered':'تم إرسال الطلب! ستصلك خلال 24 ساعة.','rewards.confirm':'تأكيد الاستبدال',
  'promo.invalid':'كود خاطئ','promo.used':'استُخدم هذا الكود مسبقًا.',
  'referral.copied':'تم نسخ الرابط!','referral.self':'لا يمكنك استخدام كودك الخاص!','referral.already':'لديك راعي بالفعل.','referral.applied':'تم تطبيق كود الإحالة!',
  'support.sent':'تم إرسال التذكرة','profile.saved':'تم تحديث الملف الشخصي!','transactions.none':'لا توجد معاملات بعد','transactions.noneSub':'ابدأ الربح لرؤية سجلك.','notifications.none':'لا توجد إشعارات'
}; 
let DICT = State.lang==='ar' ? I18N_AR : I18N_EN;
function t(k){return DICT[k]||I18N_EN[k]||k;}
function applyTranslations(){document.documentElement.lang=State.lang; document.documentElement.dir=State.lang==='ar'?'rtl':'ltr'; $$('.[data-i18n]').forEach(n=>{const k=n.dataset.i18n; if(DICT[k]) n.textContent=DICT[k];}); const b=el('langToggleLabel'); if(b)b.textContent=State.lang==='ar'?'EN':'ع';}
function setLang(l){State.lang=l==='ar'?'ar':'en';localStorage.setItem('rewords_lang',State.lang);DICT=State.lang==='ar'?I18N_AR:I18N_EN;applyTranslations();renderPage(State.currentPage);}
function setTheme(v){State.theme=v==='light'?'light':'dark';localStorage.setItem('rewords_theme',State.theme);document.documentElement.dataset.theme=State.theme;const b=el('themeToggle');if(b)b.textContent=State.theme==='dark'?'🌙':'☀️';}
function toast(title,msg,type='info'){const w=el('toastWrap');if(!w)return;const d=document.createElement('div');d.className='toast '+type;d.innerHTML=`<span class="toast-ico">${type==='success'?'✅':type==='error'?'❌':type==='warning'?'⚠️':'ℹ️'}</span><div class="toast-body"><div class="toast-title">${esc(title)}</div><div class="toast-msg">${esc(msg)}</div></div>`;w.appendChild(d);setTimeout(()=>d.remove(),4500);}
function openModal(id){const n=el(id);if(n)n.classList.add('open');}
function closeModal(id){const n=el(id);if(n)n.classList.remove('open');}
let confirmResolve=null;
function askConfirm(title,body,ok='Confirm'){return new Promise(resolve=>{confirmResolve=resolve; el('confirmDialogTitle').textContent=title;el('confirmDialogBody').textContent=body;el('confirmDialogOk').textContent=ok;openModal('confirmDialog');});}
function loading(btn,on){if(!btn)return;btn.disabled=on;btn.dataset.originalText??=btn.textContent;if(on)btn.textContent='Please wait…';else btn.textContent=btn.dataset.originalText;}
async function getCol(name, limit=200){const snap=await db.collection(name).limit(limit).get();return snap.docs.map(d=>({id:d.id,...d.data()}));}
async function safeGet(path){try{const s=await path.get();return s.exists?{id:s.id,...s.data()}:null;}catch(e){console.error(e);return null;}}
function handleErr(e,fallback='Operation failed'){console.error(e);toast('Error',e?.message||fallback,'error');}
function isActive(x){return x.active!==false && x.status!=='disabled';}
function randSafe(n){return Math.floor(Math.random()*n);}

async function loadSettings(){
  const d=await safeGet(db.collection('settings').doc('global'));
  State.settings={...DEFAULT_SETTINGS,...(d||{}),ads:{...DEFAULT_SETTINGS.ads,...(d?.ads||{}),placements:{...DEFAULT_SETTINGS.ads.placements,...(d?.ads?.placements||{})}}};
}
async function loadCatalog(){
  const names=['offers','games','surveys','rewards','providers','faqs','events','promos','posts'];
  const out=await Promise.all(names.map(n=>getCol(n,300).catch(()=>[])));
  [State.offers,State.games,State.surveys,State.rewards,State.providers,State.faqs,State.events,State.promos,State.posts]=out;
  State.offers=State.offers.filter(isActive);State.games=State.games.filter(isActive);State.surveys=State.surveys.filter(isActive);State.rewards=State.rewards.filter(isActive);
}
async function loadUserData(){
  if(!State.user){State.profile=null;State.notifications=[];State.ledger=[];return;}
  State.profile=(await safeGet(db.collection('users').doc(State.user.uid)))||{uid:State.user.uid,email:State.user.email,username:State.user.email?.split('@')[0]||'User',balance:0,status:'active'};
  const u=State.user.uid;
  const [n,l,tickets,refs1,refs2]=await Promise.all([
    db.collection('notifications').where('uid','==',u).limit(200).get().then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),
    db.collection('ledger').where('uid','==',u).limit(500).get().then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),
    db.collection('tickets').where('uid','==',u).limit(100).get().then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),
    db.collection('referrals').where('referredId','==',u).limit(100).get().then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),
    db.collection('referrals').where('referrerId','==',u).limit(100).get().then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[])
  ]);
  State.notifications=n.sort((a,b)=>(b.ts||0)-(a.ts||0));
  State.ledger=l.sort((a,b)=>(b.ts||0)-(a.ts||0));
  State.tickets=tickets.sort((a,b)=>(b.ts||0)-(a.ts||0));
  const seen=new Set(); State.referrals=[...refs1,...refs2].filter(r=>!seen.has(r.id)&&seen.add(r.id));
}
async function loadPublicStats(){}

function showMaintenance(){const o=el('maintenanceOverlay');if(o)o.classList.add('open');}
function hideMaintenance(){const o=el('maintenanceOverlay');if(o)o.classList.remove('open');}
async function checkMaintenance(){if(State.settings.maintenance && !State.user){showMaintenance();return true;}hideMaintenance();return false;}

function updateBalanceUI(){const b=Number(State.profile?.balance||0);['navBalanceText','homeBalance','wtAvailable','pfBalance','wdAvailable','topupCoinBalance'].forEach(id=>{const n=el(id);if(n)n.textContent=fmt(b);});if(el('navBalance'))el('navBalance').style.display=State.user?'flex':'none';}
function updateAuthUI(){const login=el('loginBtn');if(login)login.innerHTML=State.user?`<span>${esc(State.profile?.username||'Account')}</span>`:'<span data-i18n="auth.login">Login</span>';if(el('logoutBtnMobile'))el('logoutBtnMobile').style.display=State.user?'block':'none';}

function navigate(page){
  if(!PAGES.includes(page))page='home';
  if(AUTH_REQUIRED.has(page)&&!State.user){openModal('authModal');return;}
  if(State.settings.maintenance&&!State.user){showMaintenance();return;}
  State.currentPage=page;PAGES.forEach(p=>{const s=el('page-'+p);if(s)s.classList.toggle('active',p===page);});$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));el('drawer')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});renderPage(page);
}

function emptyState(msg='No data yet.'){return `<div class="empty-state"><div class="es-ico">🗂️</div><div class="es-title">${esc(msg)}</div></div>`;}
function offerCard(o){return `<div class="card offer-card reveal in"><div class="offer-top"><div class="offer-logo">${o.icon||'🎯'}</div><div><div class="offer-name">${esc(o.title||'Offer')}</div><div class="text-xs text-muted">${esc(o.provider||'Provider')}</div></div></div><div class="text-sm text-muted">${esc(o.description||'Complete the offer at the partner site.')}</div><div class="offer-reward">🪙 +${fmt(o.payout||0)}</div><button class="btn btn-accent btn-sm btn-block" data-action="openOffer" data-id="${o.id}">View offer</button></div>`;}
function gameCard(g){const ms=Array.isArray(g.milestones)?g.milestones:[];return `<div class="card game-card reveal in"><div class="game-cover">${g.icon||'🎮'}</div><div class="game-body"><div class="game-title">${esc(g.title||'Game')}</div><div class="text-xs text-muted">${esc(g.platform||'All platforms')}</div><div class="milestones">${ms.slice(0,3).map(m=>`<div class="milestone"><span>${m.icon||'🎯'}</span><div>${esc(m.label||'Milestone')}</div><b>+${fmt(m.reward||0)}</b></div>`).join('')}</div><a class="btn btn-accent btn-sm btn-block mt-2" href="${esc(g.link||'#')}" target="_blank" rel="noopener">Play / Open</a></div></div>`;}
function surveyCard(s){return `<div class="card survey-card reveal in"><div class="survey-ico">${s.icon||'📋'}</div><div class="survey-title">${esc(s.title||'Survey')}</div><div class="text-sm text-muted">${esc(s.description||'Share your opinion.')}</div><div class="survey-meta"><span>${s.minutes||'5'} min</span><b>+${fmt(s.payout||0)}</b></div><button class="btn btn-accent btn-sm btn-block" data-action="openSurvey" data-id="${s.id}">Start survey</button></div>`;}
function rewardCard(r){const disabled=Number(r.stock??1)<=0;return `<div class="card reward-card reveal in"><div class="reward-visual">${r.icon||'🎁'}</div><div class="reward-name">${esc(r.title||'Reward')}</div><div class="text-xs text-muted">${esc(r.category||'Reward')}</div><div class="reward-cost">🪙 ${fmt(r.price??r.cost??0)}</div><div class="text-xs text-muted">Stock: ${r.stock==null?'∞':fmt(r.stock)}</div><button class="btn btn-accent btn-sm btn-block mt-2" data-action="redeemReward" data-id="${r.id}" ${disabled?'disabled':''}>Redeem</button></div>`;}
function providerTabHtml(){return State.providers.filter(isActive).map(p=>`<button class="filter-chip" data-provider="${esc(p.id||p.name)}">${esc(p.name||'Provider')}</button>`).join('');}

function renderHome(){
  const set=(id,v)=>{const n=el(id);if(n)n.textContent=v;};set('heroOffersCount',fmt(State.offers.length));set('heroStatUsers','—');set('heroStatPaid','—');set('heroStatCoins','—');
  set('homeBalance',fmt(State.profile?.balance||0));set('homePending',fmt(State.profile?.pendingBalance||0));set('homeLifetime',fmt(State.profile?.lifetimeEarned||0));set('homeStreak',fmt(State.profile?.streak||0));
  set('tickerTrack',State.settings.announcement||'');set('accountStatusStrip',State.user?`${esc(State.profile?.username||State.user.email||'User')} · ${esc(State.profile?.status||'active')}`:'Please sign in to earn and withdraw.');
  const map={popularRewardsGrid:State.rewards.slice(0,4).map(rewardCard),topOffersGrid:State.offers.slice(0,4).map(offerCard),topGamesGrid:State.games.slice(0,4).map(gameCard),bestSurveysGrid:State.surveys.slice(0,4).map(surveyCard),activeEventsGrid:State.events.filter(e=>e.status==='active'||e.active!==false).slice(0,4).map(e=>`<div class="card"><b>${esc(e.icon||'⚡')} ${esc(e.title||'Event')}</b><div class="text-sm text-muted">${esc(e.subtitle||e.description||'')}</div></div>`),homeFaqList:State.faqs.slice(0,4).map(f=>`<div class="faq-item"><button class="faq-q" data-action="toggleFaq">${esc(f.q||f.question)}<span>＋</span></button><div class="faq-a">${esc(f.a||f.answer)}</div></div>`)};Object.entries(map).forEach(([id,arr])=>{const n=el(id);if(n)n.innerHTML=arr.join('')||emptyState();});
  updateBalanceUI();updateAuthUI();
}
function renderEarn(){renderList('adOpportunitiesList',State.offers.slice(0,6).map(offerCard),'No offers available');renderList('sponsoredTasksList',State.games.slice(0,6).map(gameCard),'No tasks available');renderList('earnOffersGrid',State.offers.map(offerCard),'No offers available');renderAds();}
function renderOffers(){filterGrid('offersGrid',State.offers,el('offersSearch')?.value.toLowerCase()||'',o=>offerCard(o));}
function renderGames(){filterGrid('gamesGrid',State.games,el('gamesSearch')?.value.toLowerCase()||'',gameCard);}
function renderSurveys(){renderList('surveysGrid',State.surveys.map(surveyCard),'No surveys available');}
function renderRewards(){renderList('rewardsGrid',State.rewards.map(rewardCard),'No rewards available');}
function filterGrid(id,data,q,builder){const n=el(id);if(!n)return;const arr=data.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));n.innerHTML=arr.map(builder).join('')||emptyState();}
function renderList(id,arr,empty){const n=el(id);if(n)n.innerHTML=arr.join('')||emptyState(empty);}
function renderAds(){
  const cfg=State.settings.ads||DEFAULT_SETTINGS.ads;const p=cfg.placements||{};
  const map={'ad-home-banner':p.banner&&cfg.adsterra?.enabled,'ad-watch-native':p.native&&cfg.adsterra?.enabled,'ad-watch-native-watch':p.native&&cfg.adsterra?.enabled,'ad-games-native':p.native&&cfg.adsterra?.enabled,'ad-smartlink':p.smartlink&&cfg.adsterra?.enabled,'monetag-direct-link':p.monetagDirect&&cfg.monetag?.enabled};
  Object.entries(map).forEach(([id,on])=>{const n=el(id);if(n)n.style.display=on?'block':'none';});
  const direct=el('monetag-direct-link');if(direct)direct.href='https://omg10.com/4/11605558';
}
function renderWatch(){const pf=State.profile||{};const used=pf.adsDate===todayKey()?(pf.adsWatchedToday||0):0;const cap=Number(State.settings.adDailyCap||15);const remaining=Math.max(0,cap-used);['watchCount','watchEarnedToday','watchRemaining'].forEach((id,i)=>setText(id,[used,used*Number(State.settings.adReward||0),remaining][i]));setText('watchHint',`Ad earnings are credited only after provider verification. Cap: ${cap}.`);const b=el('watchAdBtn');if(b)b.disabled=!State.user||remaining<=0;renderAds();}
function renderDaily(){const p=State.profile||{};const streak=Number(p.streak||0);setText('dailyStreakNum',streak);setText('dailyBonusMult',streak>=7?'x2.0':streak>=4?'x1.5':'x1.0');const g=el('dailyGrid');if(g)g.innerHTML=DAILY_PLAN.map((r,i)=>`<div class="daily-day ${((streak%7)||7)===(i+1)?'current':''}"><b>Day ${i+1}</b><span>+${fmt(r)}</span></div>`).join('');setStateButton('dailyClaimBtn',p.lastClaimDate===todayKey(),'Claimed today','Claim today');setStateButton('spinWheelBtn',p.wheelSpunDate===todayKey(),'Spun today','Spin the wheel');setStateText('scratchStatus',p.scratchDate===todayKey()?'Used today':'Tap the card to claim today');setStateText('mysteryStatus',p.mysteryDate===todayKey()?'Opened today':'Tap the box to claim today');setStateText('treasureStatus',p.treasureDate===todayKey()?'Opened today':'Tap the chest to claim today');}
function renderTasks(){renderList('tasksGrid',State.games.slice(0,8).map(gameCard),'No tasks available');}
function renderChallenges(){renderList('dailyChallengesList',[{title:'Complete 1 offer',reward:100,done:false},{title:'Open daily reward',reward:50,done:State.profile?.lastClaimDate===todayKey()}].map(c=>`<div class="card"><b>${esc(c.title)}</b><span class="badge">+${c.reward} coins</span><div>${c.done?'✅ Completed':'🟡 Pending'}</div></div>`),'No challenges');renderList('weeklyChallengesList',[], 'No weekly challenges');renderList('monthlyChallengesList',[], 'No monthly challenges');}
function renderCheckin(){setText('checkinTitle','Daily check-in');setText('checkinSub','The daily claim is your check-in.');setStateButton('checkinBtn',State.profile?.lastClaimDate===todayKey(),'Checked in','Check in');}
function renderStreaks(){setText('streakCurrent',State.profile?.streak||0);setText('streakBest',State.profile?.bestStreak||0);setText('streakFreezes',State.profile?.streakFreezes||0);const n=el('streakCalendar');if(n)n.innerHTML=Array.from({length:7},(_,i)=>`<div class="streak-day">${i+1}</div>`).join('');}
function renderReferral(){const p=State.profile||{};setText('refTotal',State.referrals.length);setText('refEarned',p.referralEarned||0);setText('refActive',State.referrals.filter(r=>r.status==='active').length);setValue('refLinkInput',location.origin+location.pathname+'?ref='+(p.referralCode||''));setText('refMilestones',Number(State.settings.referralPercent||10)+'% referral commission after verified activity.');renderList('refFriendsList',State.referrals.map(r=>`<div class="card"><b>${esc(r.referredUsername||r.referredId||'Referral')}</b><span>${esc(r.status||'pending')}</span></div>`),'No referrals yet');}
function renderLeaderboard(){const n=el('leaderboardList');if(!n)return;n.innerHTML=(State.leaderboard||[]).map((u,i)=>`<div class="leader-row"><span>#${i+1}</span><b>${esc(u.username||'User')}</b><span>${fmt(u.lifetimeEarned||0)} 🪙</span></div>`).join('')||emptyState('No leaderboard data');}
function renderTopup(){const games=State.rewards.filter(r=>(r.type||'').toLowerCase()==='topup'||String(r.category||'').toLowerCase()==='game top-up');renderList('topupGameList',games.map(g=>`<button class="reward-item ${State.selectedTopupGame?.id===g.id?'selected':''}" data-action="selectTopupGame" data-id="${g.id}" data-game="${esc(g.title)}">${g.icon||'🎮'} ${esc(g.title)}</button>`),'No top-up games configured');if(!State.selectedTopupGame&&games[0])State.selectedTopupGame=games[0];const pg=el('topupPackageGrid');if(pg){const src=(State.selectedTopupGame?.packages?.length?State.selectedTopupGame.packages:[{label:'100 Units',cost:4500},{label:'310 Units',cost:12000},{label:'520 Units',cost:18000}]);if(!State.selectedTopupPackage)State.selectedTopupPackage=src[0];pg.innerHTML=src.map(x=>`<button class="package ${State.selectedTopupPackage?.label===x.label?'selected':''}" data-action="selectPackage" data-cost="${Number(x.cost||0)}" data-label="${esc(x.label||'Package')}"><div class="pkg-name">${esc(x.label||'Package')}</div><div class="pkg-cost">${fmt(x.cost||0)}</div></button>`).join('');}setText('topupCoinBalance',State.profile?.balance||0);setText('topupSumGame',State.selectedTopupGame?.title||'—');setText('topupSumPackage',State.selectedTopupPackage?.label||'—');setText('topupSumCost',fmt(State.selectedTopupPackage?.cost||0));setText('topupSumPlayer',el('topupPlayerId')?.value||'—');setText('topupSumRegion',el('topupRegion')?.value||'—');}
function renderWithdraw(){setText('wdAvailable',State.profile?.balance||0);setText('wdPending',State.profile?.pendingWithdrawal||0);setText('wdMin',State.settings.minWithdraw||10000);setText('wdConvertHint',`Fee: ${Number(State.settings.withdrawalFeePct||0)}%`);const methods=[['PayPal','💳'],['Crypto','₿'],['Gift Card','🎁'],['Bank','🏦']];renderList('wdMethodList',methods.map(([m,i])=>`<button class="wd-method ${State.selectedWdMethod===m?'selected':''}" data-action="selectWdMethod" data-method="${m}"><span>${i}</span><b>${m}</b></button>`),'No withdrawal methods configured');updateWdSummary();}
function updateWdSummary(){const a=Number(el('wdAmount')?.value||0),fee=Math.round(a*Number(State.settings.withdrawalFeePct||0)/100),receive=Math.max(0,a-fee);setText('wdSumMethod',State.selectedWdMethod);setText('wdSumAmount',fmt(a));setText('wdSumReceive',fmt(receive));setText('wdSumFee',fmt(fee));}
function renderTransactions(){const type=State.txType||'all';const arr=(State.ledger||[]).filter(x=>type==='all'||x.type===type);renderList('transactionsList',arr.map(l=>`<div class="tx-row"><div><b>${esc(l.description||l.type||'Transaction')}</b><div class="text-xs text-muted">${new Date(l.ts||Date.now()).toLocaleString()}</div></div><strong class="${Number(l.coins)>=0?'text-success':'text-danger'}">${Number(l.coins)>=0?'+':''}${fmt(l.coins)}</strong></div>`),'No transactions');}
function renderNotifications(){const unread=State.notifications.filter(n=>!n.read).length;setText('notifBadge',unread);el('notifBadge')?.classList.toggle('hidden',unread===0);renderList('notificationsList',State.notifications.map(n=>`<div class="card ${n.read?'':'unread'}"><button class="w-full text-left" data-action="markNotif" data-id="${n.id}"><b>${esc(n.title||'Notification')}</b><div class="text-sm text-muted">${esc(n.body||'')}</div></button></div>`),'No notifications');}
function renderSupport(){setText('supOpen',State.tickets.filter(t=>['open','pending'].includes(t.status)).length);setText('supSolved',State.tickets.filter(t=>t.status==='resolved').length);renderList('myTicketsList',State.tickets.map(t=>`<div class="ticket-row"><b>${esc(t.subject||'Ticket')}</b><span>${esc(t.status||'open')}</span></div>`),'No tickets');renderList('kbGrid',State.faqs.map(f=>`<div class="card"><b>${esc(f.q||f.question)}</b><p>${esc(f.a||f.answer)}</p></div>`),'No help articles');}
function renderProfile(){const p=State.profile||{};setText('profileUsername',p.username||'User');setText('profileLevelChip','Level '+(p.level||1));setText('profileVerifiedChip',State.user?.emailVerified?'Verified':'Unverified');setText('profileMeta',p.email||State.user?.email||'');setText('profileXpLabel',fmt(p.xp||0));if(el('profileXpFill'))el('profileXpFill').style.width=Math.min(100,Number(p.xp||0)%100)+'%';['pfBalance','pfLifetime','pfOffers','pfWithdrawn','pfRefCode'].forEach(()=>{});setText('pfBalance',p.balance||0);setText('pfLifetime',p.lifetimeEarned||0);setText('pfOffers',p.offersCompleted||0);setText('pfWithdrawn',p.totalWithdrawn||0);setText('pfRefCode',p.referralCode||'—');renderList('achievementsList',[], 'No achievements yet');renderList('profileBadges',[], 'No badges yet');}
function renderSecurity(){setText('secEmailSub',State.user?.email||'');setText('secEmailIco',State.user?.emailVerified?'✅':'📧');setText('sec2faIco',State.profile?.twoFa?'✅':'🔐');renderList('loginHistoryList',[], 'Login history is only available when explicitly stored.');}
function renderFaq(){renderList('faqList',State.faqs.map(f=>`<div class="faq-item"><button class="faq-q" data-action="toggleFaq">${esc(f.q||f.question)}<span>＋</span></button><div class="faq-a">${esc(f.a||f.answer)}</div></div>`),'No FAQ entries');}
function renderTerms(){setHtml('termsContent',State.settings.terms||'Terms have not been published yet.');}
function renderPrivacy(){setHtml('privacyContent',State.settings.privacy||'Privacy policy has not been published yet.');}
function renderAntifraud(){setHtml('fraudStatusGrid',[['Account',State.profile?.status||'active'],['Email',State.user?.emailVerified?'verified':'unverified'],['Risk score',State.profile?.fraudScore||0]].map(x=>`<div class="card"><b>${esc(x[0])}</b><div>${esc(x[1])}</div></div>`).join(''));renderList('fraudLogList',[],'No fraud events on this account.');}
function renderWallet(){const p=State.profile||{};setText('wtAvailable',p.balance||0);setText('wtPending',p.pendingBalance||0);setText('wtLocked',p.lockedBalance||0);setText('wtLifetime',p.lifetimeEarned||0);setText('wtSpent',p.lifetimeSpent||0);setText('wtWithdrawn',p.totalWithdrawn||0);renderList('walletLedger',State.ledger.map(l=>`<div class="tx-row"><span>${esc(l.description||l.type)}</span><b>${fmt(l.coins)}</b></div>`),'No ledger entries');}
function renderPromo(){renderList('promoCodesGrid',State.promos.filter(p=>p.active!==false).map(p=>`<div class="card"><b>${esc(p.code)}</b><div>${esc(p.title||'Promo')}</div><span>+${fmt(p.reward||0)} coins</span><button class="btn btn-accent btn-sm" data-action="applyPromo" data-code="${esc(p.code)}">Redeem</button></div>`),'No active promo codes');}
function renderEvents(){renderList('activeEventsGrid',State.events.filter(e=>e.status==='active'||e.active!==false).map(e=>`<div class="card"><b>${esc(e.icon||'⚡')} ${esc(e.title)}</b><p>${esc(e.subtitle||e.description||'')}</p></div>`),'No active events');renderList('upcomingEventsGrid',State.events.filter(e=>e.status==='upcoming').map(e=>`<div class="card"><b>${esc(e.title)}</b></div>`),'No upcoming events');renderList('pastEventsGrid',State.events.filter(e=>e.status==='past').map(e=>`<div class="card"><b>${esc(e.title)}</b></div>`),'No past events');}
function renderBlog(){renderList('blogGrid',State.posts.map(p=>`<article class="card"><b>${esc(p.icon||'📰')} ${esc(p.title)}</b><p>${esc(p.content||'')}</p><button class="btn btn-ghost btn-sm" data-action="openArticle" data-id="${p.id}">Read</button></article>`),'No posts');}
function renderHistory(){renderTransactions();setHtml('historyList',el('transactionsList')?.innerHTML||emptyState('No history'));}
function renderOffline(){const n=el('page-offlinerewards');if(n)n.querySelector('div.card')?.insertAdjacentHTML('beforeend','<div class="text-sm text-muted">Offline rewards are displayed only when verified server records exist.</div>');}
function renderMore(){renderSupport();renderList('kbGridMore',State.faqs.map(f=>`<div class="card"><b>${esc(f.q||f.question)}</b><p>${esc(f.a||f.answer)}</p></div>`),'No help articles');}
function renderPage(p){const R={home:renderHome,earn:renderEarn,offers:renderOffers,games:renderGames,surveys:renderSurveys,watch:renderWatch,daily:renderDaily,tasks:renderTasks,challenges:renderChallenges,checkin:renderCheckin,streaks:renderStreaks,referral:renderReferral,leaderboard:renderLeaderboard,rewards:renderRewards,topup:renderTopup,withdraw:renderWithdraw,transactions:renderTransactions,notifications:renderNotifications,support:renderSupport,profile:renderProfile,security:renderSecurity,faq:renderFaq,terms:renderTerms,privacy:renderPrivacy,antifraud:renderAntifraud,wallet:renderWallet,promo:renderPromo,events:renderEvents,blog:renderBlog,article:()=>renderBlog(),history:renderHistory,offlinerewards:renderOffline,more:renderMore};try{R[p]?.();applyTranslations();}catch(e){handleErr(e,'Page rendering failed');}}

function setText(id,v){const n=el(id);if(n)n.textContent=v??'';}
function setHtml(id,v){const n=el(id);if(n)n.innerHTML=v??'';}
function setValue(id,v){const n=el(id);if(n)n.value=v??'';}
function setStateText(id,onText,offText){setText(id,onText||offText);}
function setStateButton(id,done,doneText,readyText){const b=el(id);if(!b)return;b.textContent=done?doneText:readyText;b.disabled=!!done;}

async function loadLeaderboard(){try{const s=await db.collection('users').orderBy('lifetimeEarned','desc').limit(20).get();State.leaderboard=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){State.leaderboard=[];}}
async function refreshAll(){try{await loadSettings();await loadCatalog();if(State.user)await loadUserData();await loadLeaderboard();await checkMaintenance();renderPage(State.currentPage);updateAuthUI();updateBalanceUI();}catch(e){handleErr(e,'Failed to load site data');}}

/* ---- Authentication ---- */
async function login(e){e.preventDefault();if(State.authBusy)return;State.authBusy=true;const b=el('loginBtnSubmit');loading(b,true);try{const email=el('loginEmail').value.trim();const pw=el('loginPassword').value;if(!email||!pw)throw new Error('Email and password are required.');await auth.signInWithEmailAndPassword(email,pw);closeModal('authModal');toast('Welcome','You are signed in.','success');}catch(err){handleErr(err,'Login failed');}finally{loading(b,false);State.authBusy=false;}}
async function signup(e){e.preventDefault();if(State.authBusy)return;State.authBusy=true;const b=el('signupBtnSubmit');loading(b,true);try{if(State.settings.allowSignups===false)throw new Error('New signups are currently disabled.');const username=el('signupUsername').value.trim();const email=el('signupEmail').value.trim();const pw=el('signupPassword').value;if(username.length<3)throw new Error('Username must be at least 3 characters.');if(pw.length<8)throw new Error('Password must be at least 8 characters.');const referralCode=el('signupReferral')?.value.trim().toUpperCase()||'';const cred=await auth.createUserWithEmailAndPassword(email,pw);await db.collection('users').doc(cred.user.uid).set({uid:cred.user.uid,email,username,balance:0,pendingBalance:0,lockedBalance:0,lifetimeEarned:0,lifetimeSpent:0,totalWithdrawn:0,offersCompleted:0,referralCode:username.replace(/[^a-z0-9]/gi,'').slice(0,8).toUpperCase()+'-'+cred.user.uid.slice(0,4).toUpperCase(),referredBy:referralCode||null,status:'active',xp:0,createdAt:ts(),ts:now(),lastSeenAt:ts()});await cred.user.sendEmailVerification();toast('Account created','Verification email sent.','success');closeModal('authModal');openModal('verifyModal');}catch(err){handleErr(err,'Signup failed');}finally{loading(b,false);State.authBusy=false;}}
async function resetPassword(e){e.preventDefault();try{const email=el('forgotEmail').value.trim();if(!email)throw new Error('Enter your email.');await auth.sendPasswordResetEmail(email);toast('Email sent','Password reset instructions were sent.','success');}catch(err){handleErr(err,'Could not send reset email');}}
async function googleLogin(){try{const p=new firebase.auth.GoogleAuthProvider();await auth.signInWithPopup(p);closeModal('authModal');}catch(e){handleErr(e,'Google sign-in failed');}}

/* ---- Truthful earning / atomic user actions ---- */
async function claimDaily(){if(!State.user)return openModal('authModal');const b=el('dailyClaimBtn');loading(b,true);try{const ref=db.collection('daily_claims').doc(State.user.uid+'_'+todayKey());const rewardRef=db.collection('ledger').doc(uid());await db.runTransaction(async tx=>{const [u,c]=await Promise.all([tx.get(db.collection('users').doc(State.user.uid)),tx.get(ref)]);if(c.exists)throw new Error('Already claimed today.');const p=u.data()||{};let streak=Number(p.streak||0);if(p.lastClaimDate!==yesterdayKey()&&p.lastClaimDate!==todayKey())streak=0;streak+=1;const day=((streak-1)%7)+1;const reward=DAILY_PLAN[day-1]*(streak>=7?2:streak>=4?1.5:1);tx.set(ref,{uid:State.user.uid,date:todayKey(),reward,status:'completed',createdAt:ts()});tx.update(u.ref,{balance:(Number(p.balance||0)+reward),lifetimeEarned:inc(reward),streak,bestStreak:Math.max(Number(p.bestStreak||0),streak),lastClaimDate:todayKey(),lastDailyClaimId:ref.id,xp:inc(5)});tx.set(rewardRef,{uid:State.user.uid,type:'daily',coins:reward,description:'Daily reward · day '+day,status:'completed',reference:ref.id,ts:now(),createdAt:ts()});});await loadUserData();renderPage(State.currentPage);showRewardPopup('Daily reward','+'+fmt(State.profile?.lastClaimDate===todayKey()?State.profile?.dailyReward||0:0));toast('Reward claimed','Your daily reward was credited.','success');}catch(e){handleErr(e,'Daily claim failed');}finally{loading(b,false);}}
function deterministicDailyReward(type){return type==='wheel'?150:(FIXED_DAILY_GAMES[type]||100);}
async function claimDailyGame(type){if(!State.user)return openModal('authModal');const field={wheel:'wheelSpunDate',scratch:'scratchDate',mystery:'mysteryDate',treasure:'treasureDate'}[type];const col=type+'_claims';const key=State.user.uid+'_'+todayKey();const reward=deterministicDailyReward(type);try{const claim=db.collection(col).doc(key),userRef=db.collection('users').doc(State.user.uid),ledger=db.collection('ledger').doc(uid());await db.runTransaction(async tx=>{const c=await tx.get(claim);if(c.exists)throw new Error('Already claimed today.');const u=await tx.get(userRef);const p=u.data()||{};tx.set(claim,{uid:State.user.uid,date:todayKey(),reward,status:'completed',createdAt:ts()});tx.update(userRef,{balance:Number(p.balance||0)+reward,lifetimeEarned:inc(reward),[field]:todayKey(),lastDailyGameClaimId:claim.id,lastDailyGameType:type});tx.set(ledger,{uid:State.user.uid,type:'daily',coins:reward,description:type+' daily bonus',status:'completed',reference:claim.id,ts:now(),createdAt:ts()});});await loadUserData();renderDaily();showRewardPopup(type,'+'+fmt(reward));}catch(e){handleErr(e,'Daily bonus failed');}}
async function spinWheel(){const w=el('spinWheel');try{await claimDailyGame('wheel');}catch(e){}}
async function scratchCard(){await claimDailyGame('scratch');}
async function openMystery(){await claimDailyGame('mystery');}
async function openTreasure(){await claimDailyGame('treasure');}

async function redeemReward(id){if(!State.user)return openModal('authModal');const r=State.rewards.find(x=>x.id===id);if(!r)return;const price=Number(r.price??r.cost??0);if(price<=0)return toast('Unavailable','Reward price is not configured.','warning');try{const orderRef=db.collection('orders').doc('reward_'+uid());const claimRef=db.collection('reward_claims').doc(State.user.uid+'_'+id+'_'+Date.now());const userRef=db.collection('users').doc(State.user.uid),rewardRef=db.collection('rewards').doc(id);await db.runTransaction(async tx=>{const [u,rd]=await Promise.all([tx.get(userRef),tx.get(rewardRef)]);const p=u.data()||{};const rr=rd.data()||{};const stock=rr.stock==null?Infinity:Number(rr.stock);if(stock<=0)throw new Error('Out of stock.');if(Number(p.balance||0)<price)throw new Error('Insufficient coins.');if(rr.stock!=null)tx.update(rewardRef,{stock:stock-1});tx.update(userRef,{balance:Number(p.balance||0)-price,lifetimeSpent:inc(price),lastOrderId:orderRef.id});tx.set(orderRef,{uid:State.user.uid,type:'reward',rewardId:id,item:rr.title||r.title,cost:price,status:'pending',reference:orderRef.id,createdAt:ts(),ts:now()});tx.set(claimRef,{uid:State.user.uid,rewardId:id,orderId:orderRef.id,price,createdAt:ts()});});await loadUserData();renderRewards();toast('Order created','Your reward order is pending admin fulfillment.','success');}catch(e){handleErr(e,'Reward redemption failed');}}
async function openOfferModal(id){const o=State.offers.find(x=>x.id===id);if(!o)return;openModal('offerModal');setText('offerModalTitle',o.title||'Offer');setHtml('offerModalBody',`<p>${esc(o.description||'')}</p><p class="text-muted">Reward: +${fmt(o.payout||0)} coins after provider verification.</p><a class="btn btn-accent" href="${esc(o.link||'#')}" target="_blank" rel="noopener" data-action="recordOfferClick" data-id="${o.id}">Open offer</a>`);}
async function recordOfferClick(id){try{await db.collection('offer_clicks').add({uid:State.user.uid,offerId:id,createdAt:ts(),ts:now(),status:'clicked'});toast('Offer opened','Coins are credited only after provider verification.','info');}catch(e){}closeModal('offerModal');}
async function openSurveyModal(id){const s=State.surveys.find(x=>x.id===id);if(!s)return;openModal('surveyModal');setText('surveyModalTitle',s.title||'Survey');setHtml('surveyModalBody',`<p>${esc(s.description||'')}</p><p class="text-muted">Reward: +${fmt(s.payout||0)} coins after provider verification.</p><a class="btn btn-accent" href="${esc(s.link||'#')}" target="_blank" rel="noopener" data-action="recordSurveyClick" data-id="${s.id}">Open survey</a>`);}
async function recordSurveyClick(id){try{await db.collection('survey_clicks').add({uid:State.user.uid,surveyId:id,createdAt:ts(),ts:now(),status:'clicked'});toast('Survey opened','Coins are credited only after provider verification.','info');}catch(e){}closeModal('surveyModal');}
async function watchAd(){if(!State.user)return openModal('authModal');const cap=Number(State.settings.adDailyCap||15),used=State.profile?.adsDate===todayKey()?Number(State.profile.adsWatchedToday||0):0;if(used>=cap)return toast('Limit reached','Daily ad limit reached.','warning');renderWatch();const links=[];if(State.settings.ads?.monetag?.enabled&&State.settings.ads?.placements?.monetagDirect)links.push('https://omg10.com/4/11605558');if(State.settings.ads?.adsterra?.enabled&&State.settings.ads?.placements?.smartlink)links.push('https://www.effectivecpmnetwork.com/z4tps2vcr?key=4f9ed7a11b0bab57c48fbe6c874b5a18');if(!links.length)return toast('Ads unavailable','No ad placement is enabled.','warning');await db.collection('ad_view_requests').add({uid:State.user.uid,date:todayKey(),provider:'redirect',placement:'rewarded',status:'pending',createdAt:ts(),ts:now()});window.open(links[0],'_blank','noopener');toast('Ad opened','Reward is pending provider verification; this button cannot self-credit coins.','info');}
async function promoApply(code){if(!State.user)return openModal('authModal');code=(code||el('promoInput')?.value||'').trim().toUpperCase();if(!code)return toast('Promo','Enter a promo code.','warning');try{const promoSnap=await db.collection('promos').where('code','==',code).limit(1).get();if(promoSnap.empty)throw new Error('Invalid promo code.');const promo={id:promoSnap.docs[0].id,...promoSnap.docs[0].data()};const claim=db.collection('promo_claims').doc(State.user.uid+'_'+code),userRef=db.collection('users').doc(State.user.uid),ledger=db.collection('ledger').doc(uid());await db.runTransaction(async tx=>{const [c,u]=await Promise.all([tx.get(claim),tx.get(userRef)]);if(c.exists)throw new Error('This code was already used.');if(promo.active===false)throw new Error('Promo is inactive.');const reward=Number(promo.reward||0);const p=u.data()||{};tx.set(claim,{uid:State.user.uid,code,promoId:promo.id,reward,createdAt:ts()});tx.update(userRef,{balance:Number(p.balance||0)+reward,lifetimeEarned:inc(reward),lastPromoClaimId:claim.id});tx.set(ledger,{uid:State.user.uid,type:'promo',coins:reward,description:'Promo code: '+code,status:'completed',reference:claim.id,ts:now(),createdAt:ts()});});await loadUserData();renderPromo();toast('Promo applied','+'+fmt(promo.reward||0)+' coins.','success');}catch(e){handleErr(e,'Promo failed');}}
async function submitWithdrawal(){if(!State.user)return openModal('authModal');const amount=Number(el('wdAmount')?.value||0),details={paypalEmail:el('wdPaypalEmail')?.value?.trim()||''};const min=Number(State.settings.minWithdraw||10000);if(amount<min) return toast('Withdrawal','Minimum is '+fmt(min)+' coins.','warning');if(amount>Number(State.profile?.balance||0))return toast('Withdrawal','Insufficient balance.','warning');try{const userRef=db.collection('users').doc(State.user.uid),lock=db.collection('withdrawal_locks').doc(State.user.uid),wd=db.collection('withdrawals').doc(uid()),ledger=db.collection('ledger').doc(uid());await db.runTransaction(async tx=>{const [u,l]=await Promise.all([tx.get(userRef),tx.get(lock)]);if(l.exists)throw new Error('You already have a pending withdrawal.');const p=u.data()||{};if(Number(p.balance||0)<amount)throw new Error('Insufficient balance.');const fee=Math.round(amount*Number(State.settings.withdrawalFeePct||0)/100);tx.set(lock,{uid:State.user.uid,withdrawalId:wd.id,amount,createdAt:ts()});tx.update(userRef,{balance:Number(p.balance||0)-amount,pendingWithdrawal:amount,lockedBalance:inc(amount),lastWithdrawalId:wd.id});tx.set(wd,{uid:State.user.uid,amount,fee,receive:amount-fee,method:State.selectedWdMethod,details,status:'pending',createdAt:ts(),ts:now()});tx.set(ledger,{uid:State.user.uid,type:'withdrawal',coins:-amount,description:'Withdrawal request',status:'pending',reference:wd.id,ts:now(),createdAt:ts()});});await loadUserData();renderWithdraw();renderWallet();toast('Withdrawal submitted','Your withdrawal is pending review.','success');}catch(e){handleErr(e,'Withdrawal failed');}}
async function submitTopup(){if(!State.user)return openModal('authModal');const game=State.selectedTopupGame,pack=State.selectedTopupPackage;if(!game||!pack)return toast('Top up','Select game and package first.','warning');const cost=Number(pack.cost||0);try{const uref=db.collection('users').doc(State.user.uid),order=db.collection('orders').doc('topup_'+uid());await db.runTransaction(async tx=>{const u=await tx.get(uref),p=u.data()||{};if(Number(p.balance||0)<cost)throw new Error('Insufficient coins.');tx.update(uref,{balance:Number(p.balance||0)-cost,lifetimeSpent:inc(cost),lastOrderId:order.id});tx.set(order,{uid:State.user.uid,type:'topup',game:game.title,gameId:game.id,package:pack.label,cost,playerId:el('topupPlayerId')?.value?.trim()||'',region:el('topupRegion')?.value||'',serverId:el('topupServerId')?.value?.trim()||'',status:'pending',createdAt:ts(),ts:now()});});await loadUserData();renderTopup();toast('Top-up created','Your top-up order is pending fulfillment.','success');}catch(e){handleErr(e,'Top-up failed');}}
async function applyReferral(){if(!State.user)return openModal('authModal');const code=el('refCodeInput')?.value.trim().toUpperCase();if(!code)return toast('Referral','Enter a code.','warning');try{const current=State.profile?.referredBy;if(current)throw new Error('A referrer is already assigned.');const q=await db.collection('users').where('referralCode','==',code).limit(1).get();if(q.empty)throw new Error('Invalid referral code.');const ref=q.docs[0];if(ref.id===State.user.uid)throw new Error('You cannot use your own referral code.');await db.collection('referrals').doc(State.user.uid).set({referredId:State.user.uid,referrerId:ref.id,code,createdAt:ts(),status:'pending'});await db.collection('users').doc(State.user.uid).update({referredBy:ref.id});await loadUserData();renderReferral();toast('Referral applied','Referral has been attached to your account.','success');}catch(e){handleErr(e,'Referral failed');}}
async function createTicket(){if(!State.user)return openModal('authModal');const subject=prompt('Subject');if(!subject)return;const body=prompt('Describe the issue');if(!body)return;try{await db.collection('tickets').add({uid:State.user.uid,subject,body,status:'open',priority:'normal',createdAt:ts(),ts:now()});await loadUserData();renderSupport();toast('Ticket sent','Support ticket created.','success');}catch(e){handleErr(e,'Could not create ticket');}}
async function saveProfile(){if(!State.user)return;const username=el('editUsername')?.value.trim();const country=el('editCountry')?.value.trim();if(username&&username.length<3)return toast('Profile','Username is too short.','warning');try{await db.collection('users').doc(State.user.uid).update({username,country,lastSeenAt:ts()});await loadUserData();closeModal('profileEditModal');renderProfile();toast('Profile','Profile updated.','success');}catch(e){handleErr(e,'Could not save profile');}}
async function deleteAccount(){if(!State.user)return;const ok=await askConfirm('Delete account','This will permanently disable your account and revoke sign-in.','Delete');if(!ok)return;try{await db.collection('users').doc(State.user.uid).update({status:'deleted',deletedAt:ts()});await auth.currentUser.delete();toast('Account deleted','Your account was deleted.','success');}catch(e){handleErr(e,'Account deletion failed');}}
async function logout(){await auth.signOut().catch(()=>{});navigate('home');}
async function openArticle(id){const p=State.posts.find(x=>x.id===id);if(!p)return;navigate('article');setHtml('articleBody',`<article class="card"><h1>${esc(p.title)}</h1><p>${esc(p.content||'')}</p></article>`);}
function showRewardPopup(title,msg){setText('rewardPopupAmount',title);setText('rewardPopupMsg',msg||'');openModal('rewardPopup');}

function bindEvents(){
  document.addEventListener('click',async e=>{
    const nav=e.target.closest('[data-nav]');if(nav){e.preventDefault();navigate(nav.dataset.nav);return;}
    const act=e.target.closest('[data-action]');if(act){e.preventDefault();const a=act.dataset.action,id=act.dataset.id;try{
      if(a==='openAuth')openModal('authModal'); else if(a==='logout')logout(); else if(a==='openOffer')openOfferModal(id); else if(a==='recordOfferClick')recordOfferClick(id); else if(a==='openSurvey')openSurveyModal(id); else if(a==='recordSurveyClick')recordSurveyClick(id); else if(a==='redeemReward')redeemReward(id); else if(a==='watchAd')watchAd(); else if(a==='applyPromo')promoApply(act.dataset.code); else if(a==='markNotif'){await db.collection('notifications').doc(id).update({read:true});await loadUserData();renderNotifications();} else if(a==='selectTopupGame'){State.selectedTopupGame=State.rewards.find(r=>r.id===id)||null;State.selectedTopupPackage=null;renderTopup();} else if(a==='selectPackage'){State.selectedTopupPackage={cost:Number(act.dataset.cost||0),label:act.dataset.label||''};setText('topupSumCost',fmt(State.selectedTopupPackage.cost));setText('topupSumPackage',State.selectedTopupPackage.label);} else if(a==='selectWdMethod'){State.selectedWdMethod=act.dataset.method||'PayPal';$$('#wdMethodList .wd-method').forEach(x=>x.classList.toggle('selected',x===act));updateWdSummary();} else if(a==='toggleFaq')act.closest('.faq-item')?.classList.toggle('open'); else if(a==='openTicket')createTicket(); else if(a==='openArticle')openArticle(id);
    }catch(err){handleErr(err);}};
  });
  $$('[data-toggle-pw]').forEach(b=>b.addEventListener('click',()=>{const i=el(b.dataset.togglePw);if(i)i.type=i.type==='password'?'text':'password';}));
  el('langToggle')?.addEventListener('click',()=>setLang(State.lang==='ar'?'en':'ar'));
  el('notifBtn')?.addEventListener('click',()=>navigate('notifications'));
  el('rewardPopupOk')?.addEventListener('click',()=>closeModal('rewardPopup'));
  el('secPhoneBtn')?.addEventListener('click',()=>toast('Security','Phone verification requires a Firebase phone provider and OTP flow; it is not faked here.','info'));
  $$('#page-withdraw .chip[data-amount]').forEach(b=>b.addEventListener('click',()=>{setValue('wdAmount',b.dataset.amount);updateWdSummary();}));
  ['topupPlayerId','topupRegion'].forEach(id=>el(id)?.addEventListener('input',()=>{setText('topupSumPlayer',el('topupPlayerId')?.value||'—');setText('topupSumRegion',el('topupRegion')?.value||'—');}));
  el('themeToggle')?.addEventListener('click',()=>setTheme(State.theme==='dark'?'light':'dark'));
  el('hamburger')?.addEventListener('click',()=>el('drawer')?.classList.add('open'));
  el('drawerScrim')?.addEventListener('click',()=>el('drawer')?.classList.remove('open'));
  el('toTopBtn')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
  el('loginForm')?.addEventListener('submit',login);el('signupForm')?.addEventListener('submit',signup);el('forgotForm')?.addEventListener('submit',resetPassword);
  el('googleLoginBtn')?.addEventListener('click',googleLogin);el('authModalClose')?.addEventListener('click',()=>closeModal('authModal'));el('verifyCloseBtn')?.addEventListener('click',()=>closeModal('verifyModal'));
  el('resendVerifyBtn')?.addEventListener('click',async()=>{try{await auth.currentUser?.sendEmailVerification();toast('Verification','Email resent.','success')}catch(e){handleErr(e)}});el('verifyContinueBtn')?.addEventListener('click',()=>closeModal('verifyModal'));
  el('forgotPwLink')?.addEventListener('click',()=>{el('loginForm')?.classList.add('hidden');el('forgotForm')?.classList.remove('hidden');});el('forgotBackBtn')?.addEventListener('click',()=>{el('forgotForm')?.classList.add('hidden');el('loginForm')?.classList.remove('hidden');});
  el('confirmDialogCancel')?.addEventListener('click',()=>{closeModal('confirmDialog');confirmResolve?.(false);confirmResolve=null;});el('confirmDialogOk')?.addEventListener('click',()=>{closeModal('confirmDialog');confirmResolve?.(true);confirmResolve=null;});
  el('authTabLogin')?.addEventListener('click',()=>{el('authTabLogin').classList.add('active');el('authTabSignup').classList.remove('active');el('loginForm').classList.remove('hidden');el('signupForm').classList.add('hidden');el('forgotForm').classList.add('hidden');});el('authTabSignup')?.addEventListener('click',()=>{el('authTabSignup').classList.add('active');el('authTabLogin').classList.remove('active');el('loginForm').classList.add('hidden');el('signupForm').classList.remove('hidden');el('forgotForm').classList.add('hidden');});
  el('maintenanceRetryBtn')?.addEventListener('click',refreshAll);
  el('dailyClaimBtn')?.addEventListener('click',claimDaily);el('spinWheelBtn')?.addEventListener('click',spinWheel);el('scratchCover')?.addEventListener('click',scratchCard);el('mysteryBox')?.addEventListener('click',openMystery);el('treasureChest')?.addEventListener('click',openTreasure);el('watchAdBtn')?.addEventListener('click',watchAd);el('dailyAdBonusBtn')?.addEventListener('click',watchAd);el('interstitialBtn')?.addEventListener('click',watchAd);el('checkinBtn')?.addEventListener('click',claimDaily);
  el('refCopyBtn')?.addEventListener('click',async()=>{await navigator.clipboard?.writeText(el('refLinkInput')?.value||'');toast('Referral','Link copied.','success')});el('pfRefCopyBtn')?.addEventListener('click',async()=>{await navigator.clipboard?.writeText(State.profile?.referralCode||'');toast('Referral','Code copied.','success')});el('refShareBtn')?.addEventListener('click',async()=>{const u=el('refLinkInput')?.value||location.href;if(navigator.share)await navigator.share({title:'Rewords',url:u});else await navigator.clipboard?.writeText(u);toast('Referral','Share link copied.','success')});el('refApplyBtn')?.addEventListener('click',applyReferral);
  el('topupConfirmBtn')?.addEventListener('click',submitTopup);el('wdConfirmBtn')?.addEventListener('click',submitWithdrawal);el('wdAmount')?.addEventListener('input',updateWdSummary);
  el('markAllReadBtn')?.addEventListener('click',async()=>{if(!State.user)return;const q=await db.collection('notifications').where('uid','==',State.user.uid).get();const batch=db.batch();q.docs.forEach(d=>batch.update(d.ref,{read:true}));await batch.commit();await loadUserData();renderNotifications();});el('clearNotifBtn')?.addEventListener('click',async()=>{if(!State.user)return;const q=await db.collection('notifications').where('uid','==',State.user.uid).get();const batch=db.batch();q.docs.forEach(d=>batch.delete(d.ref));await batch.commit();await loadUserData();renderNotifications();});
  el('chatSend')?.addEventListener('click',()=>{const input=el('chatInput'),body=el('chatBody');const q=input?.value.trim();if(!q||!body)return;body.insertAdjacentHTML('beforeend',`<div class="msg user"><div>${esc(q)}</div></div>`);input.value='';const low=q.toLowerCase();let a='Please open a support ticket for account-specific help.';if(low.includes('withdraw'))a='For withdrawals, choose a method, enter an amount above the minimum, then submit. Each user can have only one pending withdrawal.';else if(low.includes('earn')||low.includes('offer'))a='Complete partner offers and wait for provider verification before coins are credited.';else if(low.includes('promo'))a='Use the Promo Codes page and enter an active code once.';body.insertAdjacentHTML('beforeend',`<div class="msg admin"><div>${esc(a)}</div></div>`);body.scrollTop=body.scrollHeight;});el('editProfileBtn')?.addEventListener('click',()=>{setValue('editUsername',State.profile?.username||'');setValue('editCountry',State.profile?.country||'');openModal('profileEditModal');});el('profileEditClose')?.addEventListener('click',()=>closeModal('profileEditModal'));el('saveProfileBtn')?.addEventListener('click',saveProfile);el('deleteAccountBtn')?.addEventListener('click',deleteAccount);
  el('secVerifyEmailBtn')?.addEventListener('click',async()=>{try{if(auth.currentUser?.emailVerified)return toast('Security','Email is already verified.','info');await auth.currentUser?.sendEmailVerification();toast('Security','Verification email sent.','success')}catch(e){handleErr(e)}});el('secPasswordBtn')?.addEventListener('click',async()=>{const pw=prompt('Enter a new password (8+ characters)');if(!pw||pw.length<8)return;try{await auth.currentUser.updatePassword(pw);toast('Security','Password changed.','success')}catch(e){handleErr(e,'Password change failed')}});el('sec2faBtn')?.addEventListener('click',()=>toast('2FA','True Firebase MFA enrollment needs a configured second factor; no fake 2FA is enabled here.','info'));
  el('promoApplyBtn')?.addEventListener('click',()=>promoApply());
  el('txTypeFilter')?.addEventListener('click',e=>{const b=e.target.closest('[data-type]');if(!b)return;$$('#txTypeFilter [data-type]').forEach(x=>x.classList.toggle('active',x===b));State.txType=b.dataset.type;renderTransactions();});
  el('earnSearch')?.addEventListener('input',()=>filterGrid('earnOffersGrid',State.offers,el('earnSearch').value.toLowerCase(),offerCard));el('offersSearch')?.addEventListener('input',renderOffers);el('gamesSearch')?.addEventListener('input',renderGames);
}

auth.onAuthStateChanged(async user=>{State.user=user;if(user){await loadUserData();if(!user.emailVerified){}}else{State.profile=null;State.notifications=[];State.ledger=[];}updateAuthUI();await refreshAll();if(user&&State.currentPage==='home')renderHome();});

async function boot(){setTheme(State.theme);applyTranslations();bindEvents();await refreshAll();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.navigate=navigate;window.toast=toast;window.closeModal=closeModal;window.openModal=openModal;
